name = "graphiti"
defaultTargets = ["Graphiti"]
testDriver = "GraphitiTest"

[leanOptions]
autoImplicit = false
linter.all = false
linter.unusedSimpArgs = false
grind.warning = false
weak.linter.refine = false
weak.linter.haveLet = 0
weak.linter.oldObtain = false
weak.linter.hashCommand = false
weak.linter.docPrime = false
weak.linter.style.cdot = false
weak.linter.style.dollarSyntax = false
weak.linter.style.lambdaSyntax = false
weak.aesop.warn.applyIff = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4-nightly-testing"
rev = "nightly-testing-2025-08-06"

[[lean_lib]]
name = "Graphiti"

[[lean_exe]]
name = "graphiti"
root = "Main"

[[lean_lib]]
name = "GraphitiCore"
globs = ["Graphiti.Core.+"]

[[lean_lib]]
name = "GraphitiProjects"
globs = ["Graphiti.Projects.+"]

[[lean_lib]]
name = "GraphitiTest"
globs = ["GraphitiTest.+"]
