/-
Copyright (c) 2026 VCA Lab, EPFL. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Bourgeat, Claude
-/

import Graphiti.Projects.AsyncFifo.Bank
import Graphiti.Projects.AsyncFifo.BankR
import Graphiti.Projects.AsyncFifo.Lifting

/-!
# Composing the storage netlists

Every storage element of this development is proved twice over: once as a *contract*
(`Dff.dffSpec`, `EnReg.enSpec`, `BusReg.busSpec`, `StReg.stSpec`, `Mem.memSpec`) and once as a
*netlist of gates* refining that contract (`Dff.dff_refines`, `EnReg.en_refines`, and so on).
The graphs above them, however, are built over the contracts: `BusReg.busGraph` names `dffSpec`,
`Mem.memGraph` names `enSpec`, `Bank.bankGraph` names `busSpec`, `stSpec` and `memSpec`.  So the
gate netlists, though proved, were not *composed* into anything.

This file does the composition, bottom up.  Each step is the same one: re-read a graph in an
environment where the contract has been replaced by its netlist, and lift the componentwise
refinement with `ExprLow.refines_env`.  After it, `bankNetlistG` and `bankRNetlistG` are the two
register banks with every flip-flop, every memory cell and every bus expanded to gates.
-/

set_option linter.unusedSectionVars false

namespace Graphiti.AsyncFifo.GateRegs

open Batteries (AssocList)
open Graphiti.AsyncFifo Graphiti.AsyncFifo.Timed

-- HEADER_END (everything below is generated by gen/gen_gateregs.py)

/-! ### The three-bit Gray-pointer register, its three flip-flops expanded to gates -/

def benvG : AssocList String (TModule1 String) :=
  AssocList.cons "dff" ⟨_, Dff.dffNetlist⟩
    (BusReg.benv)

def busNetlistG := [e| BusReg.busLowered, benvG.find? ]

theorem benvG_dff : benvG.find? "dff" = .some ⟨_, Dff.dffNetlist⟩ := rfl

theorem benvG_find_ne (t : String) (h0 : t ≠ "dff") :
    benvG.find? t = BusReg.benv.find? t := by
  have e0 : ("dff" == t) = false := beq_eq_false_iff_ne.mpr (Ne.symm h0)
  simp [benvG, AssocList.find?, e0]

theorem wf_benvG : ExprLow.wf benvG.find? BusReg.busLowered := by rfl
theorem wf_busenv : ExprLow.wf BusReg.benv.find? BusReg.busLowered := by rfl

seal BusReg.benv in
theorem busNetlist_sigma :
    (⟨BusReg.busT, BusReg.busNetlist⟩ : Σ T, StringModule T) =
      ExprLow.build_module BusReg.benv.find? BusReg.busLowered := by
  dsimp -failIfUnchanged [drunfold_defs, toString, reduceAssocListfind?, reduceListPartition]
  dsimp -failIfUnchanged [reduceExprHighLower, reduceExprHighLowerProdTR, reduceExprHighLowerConnTR]
  dsimp [ExprHigh.uncurry, ExprLow.build_module_expr, ExprLow.build_module_type, ExprLow.build_module,
    ExprLow.build_module', toString]
  simp only [drenv]
  dsimp
  dsimp [Module.renamePorts, Module.mapPorts2, Module.mapOutputPorts, Module.mapInputPorts, reduceAssocListfind?]
  simp (disch := decide) only [AssocList.bijectivePortRenaming_invert]
  dsimp [Module.product]
  dsimp only [reduceModuleconnect'2]
  dsimp only [reduceEraseAll]
  dsimp; dsimp -failIfUnchanged [reduceAssocListfind?]
  unfold Module.connect''
  dsimp [Module.liftL, Module.liftR, drcomponents]
  rfl

/-- **The three-bit Gray-pointer register, its three flip-flops expanded to gates.** -/
theorem busG_refines : busNetlistG ⊑ BusReg.busSpec := by
  refine Module.refines_transitive _ ?_ BusReg.reg_refines
  refine Module.refines_transitive _ ?_ (Module.refines_eq' busNetlist_sigma.symm)
  apply ExprLow.refines_env _ wf_benvG wf_busenv
  intro i t
  by_cases h0 : t = "dff"
  · subst h0
    exact ExprLow.refines_base_of_refines i _ benvG_dff BusReg.benv_dff Dff.dff_refines
  · exact ExprLow.refines_base_of_eq i t (benvG_find_ne t h0)

/-! ### The write domain's seven-bit state register, its flip-flops expanded to gates -/

def senvG : AssocList String (TModule1 String) :=
  AssocList.cons "dff" ⟨_, Dff.dffNetlist⟩
    (StReg.senv)

def stNetlistG := [e| StReg.stLowered, senvG.find? ]

theorem senvG_dff : senvG.find? "dff" = .some ⟨_, Dff.dffNetlist⟩ := rfl

theorem senvG_find_ne (t : String) (h0 : t ≠ "dff") :
    senvG.find? t = StReg.senv.find? t := by
  have e0 : ("dff" == t) = false := beq_eq_false_iff_ne.mpr (Ne.symm h0)
  simp [senvG, AssocList.find?, e0]

theorem wf_senvG : ExprLow.wf senvG.find? StReg.stLowered := by rfl
theorem wf_stenv : ExprLow.wf StReg.senv.find? StReg.stLowered := by rfl

seal StReg.senv in
theorem stNetlist_sigma :
    (⟨StReg.stT, StReg.stNetlist⟩ : Σ T, StringModule T) =
      ExprLow.build_module StReg.senv.find? StReg.stLowered := by
  dsimp -failIfUnchanged [drunfold_defs, toString, reduceAssocListfind?, reduceListPartition]
  dsimp -failIfUnchanged [reduceExprHighLower, reduceExprHighLowerProdTR, reduceExprHighLowerConnTR]
  dsimp [ExprHigh.uncurry, ExprLow.build_module_expr, ExprLow.build_module_type, ExprLow.build_module,
    ExprLow.build_module', toString]
  simp only [drenv]
  dsimp
  dsimp [Module.renamePorts, Module.mapPorts2, Module.mapOutputPorts, Module.mapInputPorts, reduceAssocListfind?]
  simp (disch := decide) only [AssocList.bijectivePortRenaming_invert]
  dsimp [Module.product]
  dsimp only [reduceModuleconnect'2]
  dsimp only [reduceEraseAll]
  dsimp; dsimp -failIfUnchanged [reduceAssocListfind?]
  unfold Module.connect''
  dsimp [Module.liftL, Module.liftR, drcomponents]
  rfl

/-- **The write domain's seven-bit state register, its flip-flops expanded to gates.** -/
theorem stG_refines : stNetlistG ⊑ StReg.stSpec := by
  refine Module.refines_transitive _ ?_ StReg.reg_refines
  refine Module.refines_transitive _ ?_ (Module.refines_eq' stNetlist_sigma.symm)
  apply ExprLow.refines_env _ wf_senvG wf_stenv
  intro i t
  by_cases h0 : t = "dff"
  · subst h0
    exact ExprLow.refines_base_of_refines i _ senvG_dff StReg.senv_dff Dff.dff_refines
  · exact ExprLow.refines_base_of_eq i t (senvG_find_ne t h0)

/-! ### The read domain's seven-bit state register, its flip-flops expanded to gates -/

def senvRG : AssocList String (TModule1 String) :=
  AssocList.cons "dff" ⟨_, Dff.dffNetlist⟩
    (StRegR.senv)

def stRNetlistG := [e| StRegR.stLowered, senvRG.find? ]

theorem senvRG_dff : senvRG.find? "dff" = .some ⟨_, Dff.dffNetlist⟩ := rfl

theorem senvRG_find_ne (t : String) (h0 : t ≠ "dff") :
    senvRG.find? t = StRegR.senv.find? t := by
  have e0 : ("dff" == t) = false := beq_eq_false_iff_ne.mpr (Ne.symm h0)
  simp [senvRG, AssocList.find?, e0]

theorem wf_senvRG : ExprLow.wf senvRG.find? StRegR.stLowered := by rfl
theorem wf_stRenv : ExprLow.wf StRegR.senv.find? StRegR.stLowered := by rfl

seal StRegR.senv in
theorem stRNetlist_sigma :
    (⟨StRegR.stT, StRegR.stNetlist⟩ : Σ T, StringModule T) =
      ExprLow.build_module StRegR.senv.find? StRegR.stLowered := by
  dsimp -failIfUnchanged [drunfold_defs, toString, reduceAssocListfind?, reduceListPartition]
  dsimp -failIfUnchanged [reduceExprHighLower, reduceExprHighLowerProdTR, reduceExprHighLowerConnTR]
  dsimp [ExprHigh.uncurry, ExprLow.build_module_expr, ExprLow.build_module_type, ExprLow.build_module,
    ExprLow.build_module', toString]
  simp only [drenv]
  dsimp
  dsimp [Module.renamePorts, Module.mapPorts2, Module.mapOutputPorts, Module.mapInputPorts, reduceAssocListfind?]
  simp (disch := decide) only [AssocList.bijectivePortRenaming_invert]
  dsimp [Module.product]
  dsimp only [reduceModuleconnect'2]
  dsimp only [reduceEraseAll]
  dsimp; dsimp -failIfUnchanged [reduceAssocListfind?]
  unfold Module.connect''
  dsimp [Module.liftL, Module.liftR, drcomponents]
  rfl

/-- **The read domain's seven-bit state register, its flip-flops expanded to gates.** -/
theorem stRG_refines : stRNetlistG ⊑ StRegR.stSpec := by
  refine Module.refines_transitive _ ?_ StRegR.reg_refines
  refine Module.refines_transitive _ ?_ (Module.refines_eq' stRNetlist_sigma.symm)
  apply ExprLow.refines_env _ wf_senvRG wf_stRenv
  intro i t
  by_cases h0 : t = "dff"
  · subst h0
    exact ExprLow.refines_base_of_refines i _ senvRG_dff StRegR.senv_dff Dff.dff_refines
  · exact ExprLow.refines_base_of_eq i t (senvRG_find_ne t h0)

/-! ### The four-entry register file, its cells expanded to gates -/

def menvG : AssocList String (TModule1 String) :=
  AssocList.cons "cell" ⟨_, EnReg.enNetlist⟩
    (Mem.menv)

def memNetlistG := [e| Mem.memLowered, menvG.find? ]

theorem menvG_cell : menvG.find? "cell" = .some ⟨_, EnReg.enNetlist⟩ := rfl

theorem menvG_find_ne (t : String) (h0 : t ≠ "cell") :
    menvG.find? t = Mem.menv.find? t := by
  have e0 : ("cell" == t) = false := beq_eq_false_iff_ne.mpr (Ne.symm h0)
  simp [menvG, AssocList.find?, e0]

theorem wf_menvG : ExprLow.wf menvG.find? Mem.memLowered := by rfl
theorem wf_memenv : ExprLow.wf Mem.menv.find? Mem.memLowered := by rfl

seal Mem.menv in
theorem memNetlist_sigma :
    (⟨Mem.memT, Mem.memNetlist⟩ : Σ T, StringModule T) =
      ExprLow.build_module Mem.menv.find? Mem.memLowered := by
  dsimp -failIfUnchanged [drunfold_defs, toString, reduceAssocListfind?, reduceListPartition]
  dsimp -failIfUnchanged [reduceExprHighLower, reduceExprHighLowerProdTR, reduceExprHighLowerConnTR]
  dsimp [ExprHigh.uncurry, ExprLow.build_module_expr, ExprLow.build_module_type, ExprLow.build_module,
    ExprLow.build_module', toString]
  simp only [drenv]
  dsimp
  dsimp [Module.renamePorts, Module.mapPorts2, Module.mapOutputPorts, Module.mapInputPorts, reduceAssocListfind?]
  simp (disch := decide) only [AssocList.bijectivePortRenaming_invert]
  dsimp [Module.product]
  dsimp only [reduceModuleconnect'2]
  dsimp only [reduceEraseAll]
  dsimp; dsimp -failIfUnchanged [reduceAssocListfind?]
  unfold Module.connect''
  dsimp [Module.liftL, Module.liftR, drcomponents]
  rfl

/-- **The four-entry register file, its cells expanded to gates.** -/
theorem memG_refines : memNetlistG ⊑ Mem.memSpec := by
  refine Module.refines_transitive _ ?_ Mem.mem_refines
  refine Module.refines_transitive _ ?_ (Module.refines_eq' memNetlist_sigma.symm)
  apply ExprLow.refines_env _ wf_menvG wf_memenv
  intro i t
  by_cases h0 : t = "cell"
  · subst h0
    exact ExprLow.refines_base_of_refines i _ menvG_cell Mem.menv_cell EnReg.en_refines
  · exact ExprLow.refines_base_of_eq i t (menvG_find_ne t h0)

/-! ### **the write domain's whole state as gates**: state register, Gray pointer and register file -/

def kenvG : AssocList String (TModule1 String) :=
  AssocList.cons "streg" ⟨_, stNetlistG⟩
    (AssocList.cons "busreg" ⟨_, busNetlistG⟩
    (AssocList.cons "memory" ⟨_, memNetlistG⟩
    (Bank.kenv)))

def bankNetlistG := [e| Bank.bankLowered, kenvG.find? ]

theorem kenvG_streg : kenvG.find? "streg" = .some ⟨_, stNetlistG⟩ := rfl
theorem kenvG_busreg : kenvG.find? "busreg" = .some ⟨_, busNetlistG⟩ := rfl
theorem kenvG_memory : kenvG.find? "memory" = .some ⟨_, memNetlistG⟩ := rfl

theorem kenvG_find_ne (t : String) (h0 : t ≠ "streg") (h1 : t ≠ "busreg") (h2 : t ≠ "memory") :
    kenvG.find? t = Bank.kenv.find? t := by
  have e0 : ("streg" == t) = false := beq_eq_false_iff_ne.mpr (Ne.symm h0)
  have e1 : ("busreg" == t) = false := beq_eq_false_iff_ne.mpr (Ne.symm h1)
  have e2 : ("memory" == t) = false := beq_eq_false_iff_ne.mpr (Ne.symm h2)
  simp [kenvG, AssocList.find?, e0, e1, e2]

theorem wf_kenvG : ExprLow.wf kenvG.find? Bank.bankLowered := by rfl
theorem wf_bankenv : ExprLow.wf Bank.kenv.find? Bank.bankLowered := by rfl

seal Bank.kenv in
theorem bankNetlist_sigma :
    (⟨Bank.bankT, Bank.bankNetlist⟩ : Σ T, StringModule T) =
      ExprLow.build_module Bank.kenv.find? Bank.bankLowered := by
  dsimp -failIfUnchanged [drunfold_defs, toString, reduceAssocListfind?, reduceListPartition]
  dsimp -failIfUnchanged [reduceExprHighLower, reduceExprHighLowerProdTR, reduceExprHighLowerConnTR]
  dsimp [ExprHigh.uncurry, ExprLow.build_module_expr, ExprLow.build_module_type, ExprLow.build_module,
    ExprLow.build_module', toString]
  simp only [drenv]
  dsimp
  dsimp [Module.renamePorts, Module.mapPorts2, Module.mapOutputPorts, Module.mapInputPorts, reduceAssocListfind?]
  simp (disch := decide) only [AssocList.bijectivePortRenaming_invert]
  dsimp [Module.product]
  dsimp only [reduceModuleconnect'2]
  dsimp only [reduceEraseAll]
  dsimp; dsimp -failIfUnchanged [reduceAssocListfind?]
  unfold Module.connect''
  dsimp [Module.liftL, Module.liftR, drcomponents]
  rfl

/-- ****the write domain's whole state as gates**: state register, Gray pointer and register file.** -/
theorem bankG_refines : bankNetlistG ⊑ Bank.bankSpec := by
  refine Module.refines_transitive _ ?_ Bank.bank_refines
  refine Module.refines_transitive _ ?_ (Module.refines_eq' bankNetlist_sigma.symm)
  apply ExprLow.refines_env _ wf_kenvG wf_bankenv
  intro i t
  by_cases h0 : t = "streg"
  · subst h0
    exact ExprLow.refines_base_of_refines i _ kenvG_streg Bank.kenv_streg stG_refines
  by_cases h1 : t = "busreg"
  · subst h1
    exact ExprLow.refines_base_of_refines i _ kenvG_busreg Bank.kenv_busreg busG_refines
  by_cases h2 : t = "memory"
  · subst h2
    exact ExprLow.refines_base_of_refines i _ kenvG_memory Bank.kenv_memory memG_refines
  · exact ExprLow.refines_base_of_eq i t (kenvG_find_ne t h0 h1 h2)

/-! ### **the read domain's whole state as gates**: state register and Gray pointer -/

def kenvRG : AssocList String (TModule1 String) :=
  AssocList.cons "streg" ⟨_, stRNetlistG⟩
    (AssocList.cons "busreg" ⟨_, busNetlistG⟩
    (BankR.kenv))

def bankRNetlistG := [e| BankR.bankLowered, kenvRG.find? ]

theorem kenvRG_streg : kenvRG.find? "streg" = .some ⟨_, stRNetlistG⟩ := rfl
theorem kenvRG_busreg : kenvRG.find? "busreg" = .some ⟨_, busNetlistG⟩ := rfl

theorem kenvRG_find_ne (t : String) (h0 : t ≠ "streg") (h1 : t ≠ "busreg") :
    kenvRG.find? t = BankR.kenv.find? t := by
  have e0 : ("streg" == t) = false := beq_eq_false_iff_ne.mpr (Ne.symm h0)
  have e1 : ("busreg" == t) = false := beq_eq_false_iff_ne.mpr (Ne.symm h1)
  simp [kenvRG, AssocList.find?, e0, e1]

theorem wf_kenvRG : ExprLow.wf kenvRG.find? BankR.bankLowered := by rfl
theorem wf_bankRenv : ExprLow.wf BankR.kenv.find? BankR.bankLowered := by rfl

seal BankR.kenv in
theorem bankRNetlist_sigma :
    (⟨BankR.bankT, BankR.bankNetlist⟩ : Σ T, StringModule T) =
      ExprLow.build_module BankR.kenv.find? BankR.bankLowered := by
  dsimp -failIfUnchanged [drunfold_defs, toString, reduceAssocListfind?, reduceListPartition]
  dsimp -failIfUnchanged [reduceExprHighLower, reduceExprHighLowerProdTR, reduceExprHighLowerConnTR]
  dsimp [ExprHigh.uncurry, ExprLow.build_module_expr, ExprLow.build_module_type, ExprLow.build_module,
    ExprLow.build_module', toString]
  simp only [drenv]
  dsimp
  dsimp [Module.renamePorts, Module.mapPorts2, Module.mapOutputPorts, Module.mapInputPorts, reduceAssocListfind?]
  simp (disch := decide) only [AssocList.bijectivePortRenaming_invert]
  dsimp [Module.product]
  dsimp only [reduceModuleconnect'2]
  dsimp only [reduceEraseAll]
  dsimp; dsimp -failIfUnchanged [reduceAssocListfind?]
  unfold Module.connect''
  dsimp [Module.liftL, Module.liftR, drcomponents]
  rfl

/-- ****the read domain's whole state as gates**: state register and Gray pointer.** -/
theorem bankRG_refines : bankRNetlistG ⊑ BankR.bankSpec := by
  refine Module.refines_transitive _ ?_ BankR.bank_refines
  refine Module.refines_transitive _ ?_ (Module.refines_eq' bankRNetlist_sigma.symm)
  apply ExprLow.refines_env _ wf_kenvRG wf_bankRenv
  intro i t
  by_cases h0 : t = "streg"
  · subst h0
    exact ExprLow.refines_base_of_refines i _ kenvRG_streg BankR.kenv_streg stRG_refines
  by_cases h1 : t = "busreg"
  · subst h1
    exact ExprLow.refines_base_of_refines i _ kenvRG_busreg BankR.kenv_busreg busG_refines
  · exact ExprLow.refines_base_of_eq i t (kenvRG_find_ne t h0 h1)

end Graphiti.AsyncFifo.GateRegs
