/-
Copyright (c) 2026 VCA Lab, EPFL. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Bourgeat, Claude
-/

import Graphiti.Projects.AsyncFifo.SyncStage

/-!
# The synchroniser stage as three settling flip-flops

`SyncStage.lean` builds the stage out of three `settlingDffO`s, a fork, the two projections and
a packer, and proves the mathematics that makes the substitution possible (`syncOut_pack`: the
bus-level stream *is* the three bits packed).  What is left is the refinement itself, in the
shape every other netlist in this development uses: a structural invariant, one lemma per rule.

This is *not* in tension with `Sync.lean`, which proves the opposite for the plain
synchroniser: `syncNetlist ⊑ Timed.syncReg` is false, because `Dff.dff_metastable` (in `Metastability.lean`)
exhibits a clean clock, a released clear and data glitching in the aperture for which the
Boolean netlist oscillates for ever --- no instant after which its output is any constant, so
nothing an oracle can name.  The stage here escapes that not by being cleverer but by being a
different object: `settlingDffO` takes the oracle as two *input ports* (`osel`, `ojunk`), and
that it settles at all is assumed, not derived.  `Sync.lean` remains the honest account of the
wiring of two ordinary stages; this file is where the assumption is carried, one bit at a time.

The point of the file is what it removes.  Before it, `Timed.syncReg` was a primitive block and
metastability was assumed of a three-bit bus.  After it, `syncReg` is a netlist like any other,
and the assumption has moved into one primitive about one bit: `settlingDffO`, three per domain.
See `stage_refines` for exactly what the chain depends on and what merely certifies it.
-/

set_option linter.unusedSectionVars false

namespace Graphiti.AsyncFifo.GateSync

open Graphiti.AsyncFifo Graphiti.AsyncFifo.Gates Graphiti.AsyncFifo.Timed
  Graphiti.AsyncFifo.BusReg Graphiti.AsyncFifo.SyncSettle Graphiti.AsyncFifo.SyncStage
open Batteries (AssocList)

-- HEADER_END (everything below is generated by gen/gen_syncstage.py)

instance instMatch (lat su stl : Nat) : MatchInterface (stageNetlist lat su stl) (Timed.syncReg (n := 2) lat su stl) := by
  dsimp [stageNetlist, Timed.syncReg]
  solve_match_interface

/-! ### The invariant

Each node holds a prefix of what drives it, and the packer's bits are prefixes of what
their flip-flops settle to.  `h_q` is what the stage has already reported. -/

structure Wf (lat su stl : Nat) (pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk : List Bool)
    (unpB_d : List (BitVec 3)) (unpO_orc : List (Orc 2))
    (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) : Prop where
  e_clk : clkF_in = s.1
  e_d : unpB_d = s.2.1
  e_orc : unpO_orc = s.2.2.1
  w_pk_b0 : pk_b0 <+: settleOut1 su stl ff0_clk ff0_d ff0_osel ff0_ojunk
  w_pk_b1 : pk_b1 <+: settleOut1 su stl ff1_clk ff1_d ff1_osel ff1_ojunk
  w_pk_b2 : pk_b2 <+: settleOut1 su stl ff2_clk ff2_d ff2_osel ff2_ojunk
  w_ff0_clk : ff0_clk <+: clkF_in
  w_ff0_d : ff0_d <+: bitsOf 0 (wireOf lat unpB_d)
  w_ff0_osel : ff0_osel <+: selBit 0 unpO_orc
  w_ff0_ojunk : ff0_ojunk <+: junkBit 0 unpO_orc
  w_ff1_clk : ff1_clk <+: clkF_in
  w_ff1_d : ff1_d <+: bitsOf 1 (wireOf lat unpB_d)
  w_ff1_osel : ff1_osel <+: selBit 1 unpO_orc
  w_ff1_ojunk : ff1_ojunk <+: junkBit 1 unpO_orc
  w_ff2_clk : ff2_clk <+: clkF_in
  w_ff2_d : ff2_d <+: bitsOf 2 (wireOf lat unpB_d)
  w_ff2_osel : ff2_osel <+: selBit 2 unpO_orc
  w_ff2_ojunk : ff2_ojunk <+: junkBit 2 unpO_orc
  h_q : s.2.2.2 <+: pack3Out pk_b0 pk_b1 pk_b2

def ψ (lat su stl : Nat) (i : stageT) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) : Prop :=
  Wf lat su stl i.1.1 i.1.2.1 i.1.2.2 i.2.2.1 i.2.2.2.2.1.1 i.2.2.2.2.1.2.1 i.2.2.2.2.1.2.2.1 i.2.2.2.2.1.2.2.2 i.2.2.2.2.2.1.1 i.2.2.2.2.2.1.2.1 i.2.2.2.2.2.1.2.2.1 i.2.2.2.2.2.1.2.2.2 i.2.2.2.2.2.2.1 i.2.2.2.2.2.2.2.1 i.2.2.2.2.2.2.2.2.1 i.2.2.2.2.2.2.2.2.2 i.2.1 i.2.2.2.1 s

theorem Wf.init (lat su stl : Nat) : Wf lat su stl [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] ([], [], [], []) :=
  ⟨rfl, rfl, rfl, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix⟩

section SpecRules
variable (lat su stl : Nat) (sp : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3))

theorem spec_in_clk (v : List Bool) (h : sp.1 ⊏ v) :
    ((Timed.syncReg (n := 2) lat su stl).inputs.getIO ↑"clk").2 sp v (v, sp.2) := by
  rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])]; exact ⟨h, rfl⟩

theorem spec_in_d (v : List (BitVec 3)) (h : sp.2.1 ⊏ v) :
    ((Timed.syncReg (n := 2) lat su stl).inputs.getIO ↑"d").2 sp v (sp.1, v, sp.2.2) := by
  rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])]; exact ⟨h, rfl⟩

theorem spec_in_orc (v : List (Orc 2)) (h : sp.2.2.1 ⊏ v) :
    ((Timed.syncReg (n := 2) lat su stl).inputs.getIO ↑"orc").2 sp v (sp.1, sp.2.1, v, sp.2.2.2) := by
  rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])]; exact ⟨h, rfl⟩

theorem spec_out_q (v : List (BitVec 3)) (h1 : sp.2.2.2 <+: v)
    (h2 : v <+: syncOut lat su stl sp.1 sp.2.1 sp.2.2.1) :
    ((Timed.syncReg (n := 2) lat su stl).outputs.getIO ↑"q").2 sp v (sp.1, sp.2.1, sp.2.2.1, v) := by
  rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])]; exact ⟨h1, h2, rfl⟩
end SpecRules

section Cases
variable {lat su stl : Nat} {pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk : List Bool}
  {unpB_d : List (BitVec 3)} {unpO_orc : List (Orc 2)} {sp : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)}
  (Hψ : Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp)
include Hψ

theorem in_clk (v : List Bool) (h : clkF_in ⊏ v) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 (v) ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc (v, sp.2) := by
  have hm : clkF_in <+: v := h.isPrefix
  exact { e_clk := rfl
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk.trans hm
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk.trans hm
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk.trans hm
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem in_d (v : List (BitVec 3)) (h : unpB_d ⊏ v) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk (v) unpO_orc (sp.1, v, sp.2.2) := by
  have hm : unpB_d <+: v := h.isPrefix
  exact { e_clk := Hψ.e_clk
          e_d := rfl
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d.trans (bitsOf_mono (wireOf_mono hm))
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d.trans (bitsOf_mono (wireOf_mono hm))
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d.trans (bitsOf_mono (wireOf_mono hm))
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem in_orc (v : List (Orc 2)) (h : unpO_orc ⊏ v) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d (v) (sp.1, sp.2.1, v, sp.2.2.2) := by
  have hm : unpO_orc <+: v := h.isPrefix
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := rfl
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel.trans (selBit_mono hm)
          w_ff0_ojunk := Hψ.w_ff0_ojunk.trans (junkBit_mono hm)
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel.trans (selBit_mono hm)
          w_ff1_ojunk := Hψ.w_ff1_ojunk.trans (junkBit_mono hm)
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel.trans (selBit_mono hm)
          w_ff2_ojunk := Hψ.w_ff2_ojunk.trans (junkBit_mono hm)
          h_q := Hψ.h_q }

theorem int_0 (_h : ff0_clk ⊏ clkF_in) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in (clkF_in) ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0.trans (settleOut1_mono Hψ.w_ff0_clk List.prefix_rfl List.prefix_rfl List.prefix_rfl)
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := List.prefix_rfl
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_1 (_h : ff1_clk ⊏ clkF_in) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk (clkF_in) ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1.trans (settleOut1_mono Hψ.w_ff1_clk List.prefix_rfl List.prefix_rfl List.prefix_rfl)
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := List.prefix_rfl
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_2 (_h : ff2_clk ⊏ clkF_in) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk (clkF_in) ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2.trans (settleOut1_mono Hψ.w_ff2_clk List.prefix_rfl List.prefix_rfl List.prefix_rfl)
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := List.prefix_rfl
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_3 (_h : ff0_d ⊏ bitsOf 0 (wireOf lat unpB_d)) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk (bitsOf 0 (wireOf lat unpB_d)) ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0.trans (settleOut1_mono List.prefix_rfl Hψ.w_ff0_d List.prefix_rfl List.prefix_rfl)
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := List.prefix_rfl
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_4 (_h : ff1_d ⊏ bitsOf 1 (wireOf lat unpB_d)) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk (bitsOf 1 (wireOf lat unpB_d)) ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1.trans (settleOut1_mono List.prefix_rfl Hψ.w_ff1_d List.prefix_rfl List.prefix_rfl)
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := List.prefix_rfl
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_5 (_h : ff2_d ⊏ bitsOf 2 (wireOf lat unpB_d)) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk (bitsOf 2 (wireOf lat unpB_d)) ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2.trans (settleOut1_mono List.prefix_rfl Hψ.w_ff2_d List.prefix_rfl List.prefix_rfl)
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := List.prefix_rfl
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_6 (_h : ff0_osel ⊏ selBit 0 unpO_orc) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d (selBit 0 unpO_orc) ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0.trans (settleOut1_mono List.prefix_rfl List.prefix_rfl Hψ.w_ff0_osel List.prefix_rfl)
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := List.prefix_rfl
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_7 (_h : ff1_osel ⊏ selBit 1 unpO_orc) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d (selBit 1 unpO_orc) ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1.trans (settleOut1_mono List.prefix_rfl List.prefix_rfl Hψ.w_ff1_osel List.prefix_rfl)
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := List.prefix_rfl
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_8 (_h : ff2_osel ⊏ selBit 2 unpO_orc) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d (selBit 2 unpO_orc) ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2.trans (settleOut1_mono List.prefix_rfl List.prefix_rfl Hψ.w_ff2_osel List.prefix_rfl)
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := List.prefix_rfl
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_9 (_h : ff0_ojunk ⊏ junkBit 0 unpO_orc) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel (junkBit 0 unpO_orc) ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0.trans (settleOut1_mono List.prefix_rfl List.prefix_rfl List.prefix_rfl Hψ.w_ff0_ojunk)
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := List.prefix_rfl
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_10 (_h : ff1_ojunk ⊏ junkBit 1 unpO_orc) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel (junkBit 1 unpO_orc) ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1.trans (settleOut1_mono List.prefix_rfl List.prefix_rfl List.prefix_rfl Hψ.w_ff1_ojunk)
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := List.prefix_rfl
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q }

theorem int_11 (_h : ff2_ojunk ⊏ junkBit 2 unpO_orc) :
    Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel (junkBit 2 unpO_orc) unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2.trans (settleOut1_mono List.prefix_rfl List.prefix_rfl List.prefix_rfl Hψ.w_ff2_ojunk)
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := List.prefix_rfl
          h_q := Hψ.h_q }

theorem int_12 (_h : pk_b0 ⊏ settleOut1 su stl ff0_clk ff0_d ff0_osel ff0_ojunk) :
    Wf lat su stl (settleOut1 su stl ff0_clk ff0_d ff0_osel ff0_ojunk) pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := List.prefix_rfl
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q.trans (pack3Out_mono (_h.isPrefix) List.prefix_rfl List.prefix_rfl) }

theorem int_13 (_h : pk_b1 ⊏ settleOut1 su stl ff1_clk ff1_d ff1_osel ff1_ojunk) :
    Wf lat su stl pk_b0 (settleOut1 su stl ff1_clk ff1_d ff1_osel ff1_ojunk) pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := List.prefix_rfl
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q.trans (pack3Out_mono List.prefix_rfl (_h.isPrefix) List.prefix_rfl) }

theorem int_14 (_h : pk_b2 ⊏ settleOut1 su stl ff2_clk ff2_d ff2_osel ff2_ojunk) :
    Wf lat su stl pk_b0 pk_b1 (settleOut1 su stl ff2_clk ff2_d ff2_osel ff2_ojunk) clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := List.prefix_rfl
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := Hψ.h_q.trans (pack3Out_mono List.prefix_rfl List.prefix_rfl (_h.isPrefix)) }

/-- What the stage reports is a prefix of what `syncReg` promises.  `syncOut_pack` is the
theorem that makes this go through: the bus-level stream *is* the three bits packed, so
the claim reduces to monotonicity of one bit, three times. -/
theorem out_q : pack3Out pk_b0 pk_b1 pk_b2 <+: syncOut lat su stl sp.1 sp.2.1 sp.2.2.1 := by
  rw [syncOut_pack]
  refine pack3Out_mono ?_ ?_ ?_
  · exact Hψ.w_pk_b0.trans (settleOut1_mono
      (Hψ.w_ff0_clk.trans (Hψ.e_clk ▸ List.prefix_rfl))
      (Hψ.w_ff0_d.trans (bitsOf_mono (wireOf_mono (Hψ.e_d ▸ List.prefix_rfl))))
      (Hψ.w_ff0_osel.trans (selBit_mono (Hψ.e_orc ▸ List.prefix_rfl)))
      (Hψ.w_ff0_ojunk.trans (junkBit_mono (Hψ.e_orc ▸ List.prefix_rfl))))
  · exact Hψ.w_pk_b1.trans (settleOut1_mono
      (Hψ.w_ff1_clk.trans (Hψ.e_clk ▸ List.prefix_rfl))
      (Hψ.w_ff1_d.trans (bitsOf_mono (wireOf_mono (Hψ.e_d ▸ List.prefix_rfl))))
      (Hψ.w_ff1_osel.trans (selBit_mono (Hψ.e_orc ▸ List.prefix_rfl)))
      (Hψ.w_ff1_ojunk.trans (junkBit_mono (Hψ.e_orc ▸ List.prefix_rfl))))
  · exact Hψ.w_pk_b2.trans (settleOut1_mono
      (Hψ.w_ff2_clk.trans (Hψ.e_clk ▸ List.prefix_rfl))
      (Hψ.w_ff2_d.trans (bitsOf_mono (wireOf_mono (Hψ.e_d ▸ List.prefix_rfl))))
      (Hψ.w_ff2_osel.trans (selBit_mono (Hψ.e_orc ▸ List.prefix_rfl)))
      (Hψ.w_ff2_ojunk.trans (junkBit_mono (Hψ.e_orc ▸ List.prefix_rfl))))

/-- What it has reported it has reported: the report is the packer's, and the packer's
inputs only grow. -/
theorem out_wf : Wf lat su stl pk_b0 pk_b1 pk_b2 clkF_in ff0_clk ff0_d ff0_osel ff0_ojunk ff1_clk ff1_d ff1_osel ff1_ojunk ff2_clk ff2_d ff2_osel ff2_ojunk unpB_d unpO_orc (sp.1, sp.2.1, sp.2.2.1, pack3Out pk_b0 pk_b1 pk_b2) := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_orc := Hψ.e_orc
          w_pk_b0 := Hψ.w_pk_b0
          w_pk_b1 := Hψ.w_pk_b1
          w_pk_b2 := Hψ.w_pk_b2
          w_ff0_clk := Hψ.w_ff0_clk
          w_ff0_d := Hψ.w_ff0_d
          w_ff0_osel := Hψ.w_ff0_osel
          w_ff0_ojunk := Hψ.w_ff0_ojunk
          w_ff1_clk := Hψ.w_ff1_clk
          w_ff1_d := Hψ.w_ff1_d
          w_ff1_osel := Hψ.w_ff1_osel
          w_ff1_ojunk := Hψ.w_ff1_ojunk
          w_ff2_clk := Hψ.w_ff2_clk
          w_ff2_d := Hψ.w_ff2_d
          w_ff2_osel := Hψ.w_ff2_osel
          w_ff2_ojunk := Hψ.w_ff2_ojunk
          h_q := List.prefix_rfl }

end Cases

/-! ### The refinement -/

theorem int_case_0 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 0 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_0 Hψ ‹_›⟩

theorem int_case_1 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 1 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_1 Hψ ‹_›⟩

theorem int_case_2 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 2 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_2 Hψ ‹_›⟩

theorem int_case_3 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 3 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_3 Hψ ‹_›⟩

theorem int_case_4 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 4 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_4 Hψ ‹_›⟩

theorem int_case_5 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 5 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_5 Hψ ‹_›⟩

theorem int_case_6 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 6 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_6 Hψ ‹_›⟩

theorem int_case_7 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 7 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_7 Hψ ‹_›⟩

theorem int_case_8 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 8 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_8 Hψ ‹_›⟩

theorem int_case_9 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 9 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_9 Hψ ‹_›⟩

theorem int_case_10 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 10 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_10 Hψ ‹_›⟩

theorem int_case_11 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 11 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_11 Hψ ‹_›⟩

theorem int_case_12 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 12 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_12 Hψ ‹_›⟩

theorem int_case_13 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 13 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_13 Hψ ‹_›⟩

theorem int_case_14 (lat su stl : Nat) (s : List Bool × List (BitVec 3) × List (Orc 2) × List (BitVec 3)) (i mid : stageT)
    (Hψ : ψ lat su stl i s)
    (Hrule : ((stageNetlist lat su stl).internals.getD 14 (fun _ _ => False)) i mid) :
    ∃ s', existSR (Timed.syncReg (n := 2) lat su stl).internals s s' ∧ ψ lat su stl mid s' := by
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨⟨c_pk_b0, c_pk_b1, c_pk_b2⟩, c_unpB_d, c_clkF_in, c_unpO_orc, ⟨c_ff0_clk, c_ff0_d, c_ff0_osel, c_ff0_ojunk⟩, ⟨c_ff1_clk, c_ff1_d, c_ff1_osel, c_ff1_ojunk⟩, ⟨c_ff2_clk, c_ff2_d, c_ff2_osel, c_ff2_ojunk⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_14 Hψ ‹_›⟩

theorem stageNetlist_internals_eq (lat su stl : Nat) : (stageNetlist lat su stl).internals = [(stageNetlist lat su stl).internals.getD 0 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 1 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 2 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 3 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 4 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 5 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 6 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 7 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 8 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 9 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 10 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 11 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 12 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 13 (fun _ _ => False), (stageNetlist lat su stl).internals.getD 14 (fun _ _ => False)] := rfl

theorem refines_ψ (lat su stl : Nat) : (stageNetlist lat su stl) ⊑_{ψ lat su stl} (Timed.syncReg (n := 2) lat su stl) := by
  intro i s Hψ
  constructor
  · intro ident mid_i v Hrule
    obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
    dsimp only [ψ] at Hψ
    obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid_i
    case_transition Hcontains : Module.inputs (stageNetlist lat su stl), ident, (PortMap.getIO_not_contained_false' Hrule)
    dsimp only [stageNetlist] at Hcontains
    simp at Hcontains
    rcases Hcontains with h | h | h
    all_goals subst h
    all_goals rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])] at Hrule
    all_goals dsimp only at Hrule
    all_goals simp only [Prod.mk.injEq, and_assoc] at Hrule
    all_goals repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
    all_goals first
      | exact ⟨_, _, spec_in_clk lat su stl s _ (by rw [← Hψ.e_clk]; assumption), existSR_reflexive, in_clk Hψ _ ‹_›⟩
      | exact ⟨_, _, spec_in_d lat su stl s _ (by rw [← Hψ.e_d]; assumption), existSR_reflexive, in_d Hψ _ ‹_›⟩
      | exact ⟨_, _, spec_in_orc lat su stl s _ (by rw [← Hψ.e_orc]; assumption), existSR_reflexive, in_orc Hψ _ ‹_›⟩
  · intro ident mid_i v Hrule
    obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
    dsimp only [ψ] at Hψ
    obtain ⟨⟨m_pk_b0, m_pk_b1, m_pk_b2⟩, m_unpB_d, m_clkF_in, m_unpO_orc, ⟨m_ff0_clk, m_ff0_d, m_ff0_osel, m_ff0_ojunk⟩, ⟨m_ff1_clk, m_ff1_d, m_ff1_osel, m_ff1_ojunk⟩, ⟨m_ff2_clk, m_ff2_d, m_ff2_osel, m_ff2_ojunk⟩⟩ := mid_i
    case_transition Hcontains : Module.outputs (stageNetlist lat su stl), ident, (PortMap.getIO_not_contained_false' Hrule)
    dsimp only [stageNetlist] at Hcontains
    simp at Hcontains
    subst Hcontains
    rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])] at Hrule
    dsimp only at Hrule
    simp only [Prod.mk.injEq, and_assoc] at Hrule
    repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
    exact ⟨s, _, existSR_reflexive, spec_out_q lat su stl s _ Hψ.h_q (out_q Hψ), out_wf Hψ⟩
  · intro rule mid_i Hin Hrule
    rw [stageNetlist_internals_eq] at Hin
    simp only [List.mem_cons, List.not_mem_nil, or_false] at Hin
    rcases Hin with h | h | h | h | h | h | h | h | h | h | h | h | h | h | h
    · subst h; exact int_case_0 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_1 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_2 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_3 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_4 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_5 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_6 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_7 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_8 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_9 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_10 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_11 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_12 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_13 lat su stl s i mid_i Hψ Hrule
    · subst h; exact int_case_14 lat su stl s i mid_i Hψ Hrule

theorem refines_initial (lat su stl : Nat) :
    Module.refines_initial (stageNetlist lat su stl) (Timed.syncReg (n := 2) lat su stl) (ψ lat su stl) := by
  intro i hi
  obtain ⟨⟨pk_b0, pk_b1, pk_b2⟩, unpB_d, clkF_in, unpO_orc, ⟨ff0_clk, ff0_d, ff0_osel, ff0_ojunk⟩, ⟨ff1_clk, ff1_d, ff1_osel, ff1_ojunk⟩, ⟨ff2_clk, ff2_d, ff2_osel, ff2_ojunk⟩⟩ := i
  dsimp only [stageNetlist] at hi
  simp only [Prod.mk.injEq, and_assoc] at hi
  obtain ⟨rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩ := hi
  exact ⟨([], [], [], []), rfl, Wf.init lat su stl⟩

/-- **The three settling flip-flops refine the synchroniser stage**, so `Timed.syncReg` is
no longer a primitive: it is three one-bit stages and a packer.

What the chain *depends* on is the definition of `SyncStage.settlingDffO` --- its output is
`settleOut1`, the oracle-driven stream --- together with `SyncStage.syncOut_pack`.  That the
primitive is no stronger than a settling flip-flop is certified separately by
`SyncStage.settleOut1_settleOut` (it meets `Timed.SettleOut`) and by `SyncSettle.settle_orc`
(any three bits meeting `SettleOut` admit an oracle making them a `syncReg`).  Those two are
leaves of the development, not links in it: they justify the choice of primitive rather than
being consumed by this proof. -/
theorem stage_refines (lat su stl : Nat) : (stageNetlist lat su stl) ⊑ (Timed.syncReg (n := 2) lat su stl) :=
  ⟨inferInstance, ψ lat su stl, refines_ψ lat su stl, refines_initial lat su stl⟩

end Graphiti.AsyncFifo.GateSync
