/-
Copyright (c) 2026 VCA Lab, EPFL. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Bourgeat, Claude
-/

import Graphiti.Projects.AsyncFifo.BusReg

/-!
# Experiment: the structural invariant as an indexed predicate

Every netlist refinement in this development is generated by a script in `gen/`, because the
invariant `Wf` is a flat record with one field per wire and the module's `internals` is a literal
list of rules, so each rule needs its own lemma re-establishing every field -- and in
`BusReg.lean` fifteen of each lemma's sixteen fields are unchanged copies of the hypothesis.
That is index bookkeeping, and it is the only reason the scripts exist.

This file redoes the whole of `BusReg`'s refinement with the wires as an *index type* and `Wf`
quantified over it, and reaches the same theorem:

    IndexedWf.reg_refines : busNetlist ⊑ busSpec

which is `BusReg.reg_refines` verbatim.  That equality of statements is the point: an invariant
that never had to support the output obligation could have been too weak, and the twelve rule
cases would then have been easy and worthless.  They are not.

The per-rule lemmas collapse into three facts -- `Wf_set` for a connection, `Wf_env` for an
input, `out_q` for the output -- and one tactic proves every connection, so each of the twelve is
a single line.  What is netlist-specific is `W`, `drv`, `drv_mono`, `drv_mono_env`, `wires`,
`out_q` and those twelve lines: about sixty, against the six hundred and twenty-eight the
generator emits.  `Wf`, `Wf_step`, `Wf_set`, `Wf_env`, `upd`, `upd_ge` and `cast_self` mention no
netlist at all and would move to a shared file.

Two things cost a debugging round and are worth knowing before doing this to another netlist.
A port's value arrives under an `Eq.mp` between identical types: `cast_eq` will not fire on it,
because the proof is not syntactically `rfl`, so `cast_self` is needed.  And `wires` must be
reduced in a hypothesis *before* it meets the module's rules -- `dsimp only [wires] at ho` is the
difference between the output case closing immediately and `isDefEq` running out of heartbeats.
-/

namespace Graphiti.AsyncFifo.IndexedWf

open Graphiti
open Graphiti.AsyncFifo Graphiti.AsyncFifo.Gates Graphiti.AsyncFifo.Timed
open Graphiti.AsyncFifo.BusReg Graphiti.AsyncFifo.Dff

/-! ### The netlist -/

/-- The twelve driven wires of `busNetlist`. -/
inductive W | pk0 | pk1 | pk2
            | f0clk | f0d | f0crn | f1clk | f1d | f1crn | f2clk | f2d | f2crn
  deriving DecidableEq

/-- What drives each wire: one line per wire, and the only place the shape of the netlist is
written down.  This replaces the sixteen-field `Wf` record. -/
def drv (clk crn : List Bool) (d : List (BitVec 3)) (w : W → List Bool) : W → List Bool
  | .pk0 => dffOut (w .f0clk) (w .f0d) (w .f0crn)
  | .pk1 => dffOut (w .f1clk) (w .f1d) (w .f1crn)
  | .pk2 => dffOut (w .f2clk) (w .f2d) (w .f2crn)
  | .f0clk | .f1clk | .f2clk => clk
  | .f0crn | .f1crn | .f2crn => crn
  | .f0d => bitsOf 0 d
  | .f1d => bitsOf 1 d
  | .f2d => bitsOf 2 d

/-- Every wire holds a prefix of what drives it. -/
def Wf (clk crn : List Bool) (d : List (BitVec 3)) (w : W → List Bool) : Prop :=
  ∀ k, w k <+: drv clk crn d w k

/-- The netlist is monotone in its wires. -/
theorem drv_mono {clk crn d} {w w' : W → List Bool} (h : ∀ j, w j <+: w' j) (k : W) :
    drv clk crn d w k <+: drv clk crn d w' k := by
  cases k <;> simp only [drv] <;>
    first
      | exact List.prefix_rfl
      | exact dffOut_mono (h .f0clk) (h .f0d) (h .f0crn)
      | exact dffOut_mono (h .f1clk) (h .f1d) (h .f1crn)
      | exact dffOut_mono (h .f2clk) (h .f2d) (h .f2crn)

/-! ### The two facts that replace every per-rule lemma -/

/-- One wire takes a new value, the rest stand. -/
def upd (w : W → List Bool) (k : W) (v : List Bool) : W → List Bool :=
  fun j => if j = k then v else w j

theorem upd_ge {w : W → List Bool} {k v} (h1 : w k <+: v) : ∀ j, w j <+: upd w k v j := by
  intro j; by_cases hj : j = k
  · subst hj; simpa [upd] using h1
  · simp only [upd, if_neg hj]; exact List.prefix_rfl

/-- Any step that only grows wires, and grows none past what currently drives it, preserves the
invariant. -/
theorem Wf_step {clk crn d} {w w' : W → List Bool} (hw : Wf clk crn d w)
    (hle : ∀ j, w j <+: w' j) (hd : ∀ j, w' j <+: drv clk crn d w j) : Wf clk crn d w' :=
  fun k => (hd k).trans (drv_mono hle k)

/-- **The one lemma that replaces every `int_k`**: the shape every connection rule has. -/
theorem Wf_set {clk crn d} {w : W → List Bool} (hw : Wf clk crn d w) (k : W) (v : List Bool)
    (h1 : w k <+: v) (h2 : v <+: drv clk crn d w k) : Wf clk crn d (upd w k v) := by
  refine Wf_step hw (upd_ge h1) (fun j => ?_); by_cases hj : j = k
  · subst hj; simpa [upd] using h2
  · simp only [upd, if_neg hj]; exact hw j

/-- The reported output only grows, so its clause survives any step.  The one clause that is
about the block's interface rather than its wiring. -/
theorem hq_set {w : W → List Bool} {k v q} (h1 : w k <+: v)
    (hq : q <+: pack3Out (w .pk0) (w .pk1) (w .pk2)) :
    q <+: pack3Out (upd w k v .pk0) (upd w k v .pk1) (upd w k v .pk2) :=
  hq.trans (pack3Out_mono (upd_ge h1 _) (upd_ge h1 _) (upd_ge h1 _))

theorem Wf_init {clk crn d} : Wf clk crn d (fun _ => []) := fun _ => List.nil_prefix

/-! ### The bridge to the reduced module -/

/-- The reduced state is a nested product; `wires` reads it as an assignment. -/
def wires (i : busT) : W → List Bool
  | .pk0 => i.1.1 | .pk1 => i.1.2.1 | .pk2 => i.1.2.2
  | .f0clk => i.2.2.2.2.1.1 | .f0d => i.2.2.2.2.1.2.1 | .f0crn => i.2.2.2.2.1.2.2
  | .f1clk => i.2.2.2.2.2.1.1 | .f1d => i.2.2.2.2.2.1.2.1 | .f1crn => i.2.2.2.2.2.1.2.2
  | .f2clk => i.2.2.2.2.2.2.1 | .f2d => i.2.2.2.2.2.2.2.1 | .f2crn => i.2.2.2.2.2.2.2.2

def psi (i : busT) (s : List Bool × List (BitVec 3) × List Bool × List (BitVec 3)) : Prop :=
  Wf s.1 s.2.2.1 s.2.1 (wires i) ∧ i.2.2.2.1 = s.1 ∧ i.2.1 = s.2.1 ∧ i.2.2.1 = s.2.2.1
    ∧ s.2.2.2 <+: pack3Out (wires i .pk0) (wires i .pk1) (wires i .pk2)

/-! ### One tactic for every connection

Destructure the two states, split the rule, re-establish the invariant: the same text for all
twelve rules.  Only *which* wire advances differs, and that is the argument. -/

syntax "connect_case " term : tactic
set_option hygiene false in
macro_rules
  | `(tactic| connect_case $w:term) => `(tactic| (
      obtain ⟨⟨pk0, pk1, pk2⟩, ud, cr, ck, ⟨a0,a1,a2⟩, ⟨b0,b1,b2⟩, ⟨c0,c1,c2⟩⟩ := i
      obtain ⟨⟨_,_,_⟩, _, _, _, ⟨_,_,_⟩, ⟨_,_,_⟩, ⟨_,_,_⟩⟩ := mid
      have Hr := Hrule.1 rfl; clear Hrule
      obtain ⟨⟨⟨_,_,_⟩,_,_,_,⟨_,_,_⟩,⟨_,_,_⟩,⟨_,_,_⟩⟩, out, Hr⟩ := Hr
      simp only [Prod.mk.injEq, and_assoc] at Hr
      repeat' (obtain ⟨hh, Hr⟩ := Hr; try subst hh)
      obtain ⟨hw, e1, e2, e3, hq⟩ := H
      refine ⟨s, existSR_reflexive, ?_, e1, e2, e3, ?_⟩
      · have key := Wf_set hw $w _ (‹_ ⊏ _›).isPrefix (by
          simp only [drv, wires]
          first
            | exact e1 ▸ List.prefix_rfl
            | exact e3 ▸ List.prefix_rfl
            | exact e2 ▸ List.prefix_rfl
            | assumption)
        intro j; have hj := key j; revert hj; cases j <;> simp [wires, upd, drv]
      · have key := hq_set (k := $w) (‹_ ⊏ _›).isPrefix hq
        revert key; simp [wires, upd]))

/-! All twelve connections, one line each. -/

theorem case_0 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 0 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f0clk

theorem case_1 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 1 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f1clk

theorem case_2 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 2 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f2clk

theorem case_3 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 3 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f0crn

theorem case_4 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 4 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f1crn

theorem case_5 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 5 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f2crn

theorem case_6 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 6 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f0d

theorem case_7 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 7 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f1d

theorem case_8 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 8 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f2d

theorem case_9 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 9 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.pk0

theorem case_10 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 10 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.pk1

theorem case_11 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 11 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.pk2

/-! ### The rest of the refinement

`drv` is monotone in the block's own inputs as well as in its wires, which is the one fact the
three input rules need; the output rule needs that what the packer holds is a prefix of what the
specification reports.  Both are as uniform as `Wf_set`. -/

theorem drv_mono_env {clk clk' crn crn' : List Bool} {d d' : List (BitVec 3)}
    (hc : clk <+: clk') (hr : crn <+: crn') (hd : d <+: d') {w : W → List Bool} (k : W) :
    drv clk crn d w k <+: drv clk' crn' d' w k := by
  cases k <;> simp only [drv] <;>
    first | exact List.prefix_rfl | exact hc | exact hr | exact bitsOf_mono hd

/-- Growing an input preserves the invariant: the one lemma behind all three input rules. -/
theorem Wf_env {clk clk' crn crn' : List Bool} {d d' : List (BitVec 3)} {w : W → List Bool}
    (hw : Wf clk crn d w) (hc : clk <+: clk') (hr : crn <+: crn') (hd : d <+: d') :
    Wf clk' crn' d' w := fun k => (hw k).trans (drv_mono_env hc hr hd k)

/-- What the block reports is a prefix of what the specification says: monotonicity composed
along the netlist, which here is three uses of one hypothesis. -/
theorem out_q {clk crn d} {w : W → List Bool} (hw : Wf clk crn d w) :
    pack3Out (w .pk0) (w .pk1) (w .pk2) <+: busOut clk d crn := by
  refine pack3Out_mono ?_ ?_ ?_
  · exact (hw .pk0).trans (dffOut_mono (hw .f0clk) (hw .f0d) (hw .f0crn))
  · exact (hw .pk1).trans (dffOut_mono (hw .f1clk) (hw .f1d) (hw .f1crn))
  · exact (hw .pk2).trans (dffOut_mono (hw .f2clk) (hw .f2d) (hw .f2crn))

/-- A port's value arrives under an `Eq.mp` between identical types.  Lean's proof irrelevance is
definitional, so the cast is the identity by `rfl` -- but `cast_eq` cannot fire on it, because the
proof is not syntactically `rfl`, and leaving it in place makes `isDefEq` unfold `getIO` looking
for a way through.  Rewriting with this first is what keeps the output case cheap. -/
theorem cast_self {α : Type _} (h : α = α) (x : α) : cast h x = x := rfl

set_option maxHeartbeats 1000000 in
theorem refines_psi : busNetlist ⊑_{psi} busSpec := by
  intro i s H
  constructor
  · intro ident mid_i v Hrule
    obtain ⟨⟨pk0, pk1, pk2⟩, ud, cr, ck, ⟨a0,a1,a2⟩, ⟨b0,b1,b2⟩, ⟨c0,c1,c2⟩⟩ := i
    obtain ⟨⟨_,_,_⟩, _, _, _, ⟨_,_,_⟩, ⟨_,_,_⟩, ⟨_,_,_⟩⟩ := mid_i
    obtain ⟨hw, e1, e2, e3, hq⟩ := H
    case_transition Hcontains : Module.inputs busNetlist, ident,
      (PortMap.getIO_not_contained_false' Hrule)
    dsimp only [busNetlist] at Hcontains
    simp at Hcontains
    rcases Hcontains with h | h | h <;> subst h <;>
      rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])] at Hrule <;>
      dsimp only at Hrule <;>
      simp only [Prod.mk.injEq, and_assoc] at Hrule <;>
      obtain ⟨hpre, Hrule⟩ := Hrule <;>
      repeat' (obtain ⟨hh, Hrule⟩ := Hrule; try subst hh)
    -- The port's identity is decided by `hpre`'s type; the three proofs are one shape.
    all_goals simp only [eq_mp_eq_cast] at hpre
    all_goals first
      | exact ⟨_, _, BusReg.spec_in_clk s _ (by rw [← e1]; exact hpre), existSR_reflexive,
          Wf_env hw (e1 ▸ hpre.isPrefix) List.prefix_rfl List.prefix_rfl, rfl, e2, e3, hq⟩
      | exact ⟨_, _, BusReg.spec_in_d s _ (by rw [← e2]; exact hpre), existSR_reflexive,
          Wf_env hw List.prefix_rfl List.prefix_rfl (e2 ▸ hpre.isPrefix), e1, rfl, e3, hq⟩
      | exact ⟨_, _, BusReg.spec_in_clrn s _ (by rw [← e3]; exact hpre), existSR_reflexive,
          Wf_env hw List.prefix_rfl (e3 ▸ hpre.isPrefix) List.prefix_rfl, e1, e2, rfl, hq⟩
  · intro ident mid_i v Hrule
    obtain ⟨⟨pk0, pk1, pk2⟩, ud, cr, ck, ⟨a0,a1,a2⟩, ⟨b0,b1,b2⟩, ⟨c0,c1,c2⟩⟩ := i
    obtain ⟨⟨_,_,_⟩, _, _, _, ⟨_,_,_⟩, ⟨_,_,_⟩, ⟨_,_,_⟩⟩ := mid_i
    obtain ⟨hw, e1, e2, e3, hq⟩ := H
    case_transition Hcontains : Module.outputs busNetlist, ident,
      (PortMap.getIO_not_contained_false' Hrule)
    dsimp only [busNetlist] at Hcontains
    simp at Hcontains
    subst Hcontains
    rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])] at Hrule
    dsimp only at Hrule
    simp only [Prod.mk.injEq, and_assoc] at Hrule
    repeat' (obtain ⟨hh, Hrule⟩ := Hrule; try subst hh)
    -- Apply the specification's rule rather than rewriting the goal: rewriting is what puts a
    -- cast on the port's value and sends `isDefEq` off into the weeds.
    -- The port's value comes out under an `Eq.mp`; leaving it there is what sends `isDefEq`
    -- off into the weeds, because it has to see through `getIO` to discharge the cast.
    simp only [eq_mp_eq_cast, cast_self]
    dsimp only [wires] at hq
    have ho := out_q hw
    dsimp only [wires] at ho
    exact ⟨s, _, existSR_reflexive, BusReg.spec_out_q s _ hq ho,
      hw, e1, e2, e3, List.prefix_rfl⟩
  · intro rule mid_i Hin Hrule
    rw [BusReg.busNetlist_internals_eq] at Hin
    simp only [List.mem_cons, List.not_mem_nil, or_false] at Hin
    rcases Hin with h|h|h|h|h|h|h|h|h|h|h|h
    · subst h; exact case_0 s i mid_i H Hrule
    · subst h; exact case_1 s i mid_i H Hrule
    · subst h; exact case_2 s i mid_i H Hrule
    · subst h; exact case_3 s i mid_i H Hrule
    · subst h; exact case_4 s i mid_i H Hrule
    · subst h; exact case_5 s i mid_i H Hrule
    · subst h; exact case_6 s i mid_i H Hrule
    · subst h; exact case_7 s i mid_i H Hrule
    · subst h; exact case_8 s i mid_i H Hrule
    · subst h; exact case_9 s i mid_i H Hrule
    · subst h; exact case_10 s i mid_i H Hrule
    · subst h; exact case_11 s i mid_i H Hrule

theorem refines_initial : Module.refines_initial busNetlist busSpec psi := by
  intro i hi
  obtain ⟨⟨pk0, pk1, pk2⟩, ud, cr, ck, ⟨a0,a1,a2⟩, ⟨b0,b1,b2⟩, ⟨c0,c1,c2⟩⟩ := i
  dsimp only [busNetlist] at hi
  simp only [Prod.mk.injEq, and_assoc] at hi
  obtain ⟨rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩ := hi
  refine ⟨([], [], [], []), rfl, ?_, rfl, rfl, rfl, List.nil_prefix⟩
  intro k; cases k <;> exact List.nil_prefix

/-- **The theorem the generated proof reaches, by the indexed route.** -/
theorem reg_refines : busNetlist ⊑ busSpec :=
  ⟨inferInstance, psi, refines_psi, refines_initial⟩

end Graphiti.AsyncFifo.IndexedWf
