/-
Copyright (c) 2026 VCA Lab, EPFL. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Bourgeat, Claude
-/

import Graphiti.Projects.AsyncFifo.BusReg

/-!
# Experiment: the structural invariant as an indexed predicate

Every netlist refinement in this development is generated by a script in `gen/`, because the
invariant `Wf` is a flat record with one field per wire and the module's `internals` is a literal
list of rules, so each rule needs its own lemma re-establishing every field -- and in
`BusReg.lean` fifteen of each lemma's sixteen fields are unchanged copies of the hypothesis.
That is index bookkeeping, and it is the only reason the scripts exist.

This file redoes `BusReg`'s twelve connection rules with the wires as an *index type* and `Wf`
quantified over it.  The per-rule lemmas then collapse into two facts -- `Wf_set` for the
invariant and `hq_set` for the reported output -- and each rule becomes one line.  Nothing here
is generated.

What is netlist-specific is `W`, `drv`, `drv_mono`, `wires` and the twelve one-line cases:
about forty lines, against the three hundred and eighty-eight the generator emits for the same
twelve rules.  `Wf`, `Wf_step`, `Wf_set`, `upd` and `upd_ge` mention no netlist at all and would
move to a shared file.

Not covered here: the three input rules, the output rule, and the assembly into
`refines_ψ`/`refines_initial`, which the generator also emits.  They shrink the same way but are
not the interesting part.  For a gate netlist the `first` alternation in `drv_mono` and in the
tactic would need the gate monotonicity lemmas as well.
-/

namespace Graphiti.AsyncFifo.IndexedWf

open Graphiti
open Graphiti.AsyncFifo Graphiti.AsyncFifo.Gates Graphiti.AsyncFifo.Timed
open Graphiti.AsyncFifo.BusReg Graphiti.AsyncFifo.Dff

/-! ### The netlist -/

/-- The twelve driven wires of `busNetlist`. -/
inductive W | pk0 | pk1 | pk2
            | f0clk | f0d | f0crn | f1clk | f1d | f1crn | f2clk | f2d | f2crn
  deriving DecidableEq

/-- What drives each wire: one line per wire, and the only place the shape of the netlist is
written down.  This replaces the sixteen-field `Wf` record. -/
def drv (clk crn : List Bool) (d : List (BitVec 3)) (w : W → List Bool) : W → List Bool
  | .pk0 => dffOut (w .f0clk) (w .f0d) (w .f0crn)
  | .pk1 => dffOut (w .f1clk) (w .f1d) (w .f1crn)
  | .pk2 => dffOut (w .f2clk) (w .f2d) (w .f2crn)
  | .f0clk | .f1clk | .f2clk => clk
  | .f0crn | .f1crn | .f2crn => crn
  | .f0d => bitsOf 0 d
  | .f1d => bitsOf 1 d
  | .f2d => bitsOf 2 d

/-- Every wire holds a prefix of what drives it. -/
def Wf (clk crn : List Bool) (d : List (BitVec 3)) (w : W → List Bool) : Prop :=
  ∀ k, w k <+: drv clk crn d w k

/-- The netlist is monotone in its wires. -/
theorem drv_mono {clk crn d} {w w' : W → List Bool} (h : ∀ j, w j <+: w' j) (k : W) :
    drv clk crn d w k <+: drv clk crn d w' k := by
  cases k <;> simp only [drv] <;>
    first
      | exact List.prefix_rfl
      | exact dffOut_mono (h .f0clk) (h .f0d) (h .f0crn)
      | exact dffOut_mono (h .f1clk) (h .f1d) (h .f1crn)
      | exact dffOut_mono (h .f2clk) (h .f2d) (h .f2crn)

/-! ### The two facts that replace every per-rule lemma -/

/-- One wire takes a new value, the rest stand. -/
def upd (w : W → List Bool) (k : W) (v : List Bool) : W → List Bool :=
  fun j => if j = k then v else w j

theorem upd_ge {w : W → List Bool} {k v} (h1 : w k <+: v) : ∀ j, w j <+: upd w k v j := by
  intro j; by_cases hj : j = k
  · subst hj; simpa [upd] using h1
  · simp only [upd, if_neg hj]; exact List.prefix_rfl

/-- Any step that only grows wires, and grows none past what currently drives it, preserves the
invariant. -/
theorem Wf_step {clk crn d} {w w' : W → List Bool} (hw : Wf clk crn d w)
    (hle : ∀ j, w j <+: w' j) (hd : ∀ j, w' j <+: drv clk crn d w j) : Wf clk crn d w' :=
  fun k => (hd k).trans (drv_mono hle k)

/-- **The one lemma that replaces every `int_k`**: the shape every connection rule has. -/
theorem Wf_set {clk crn d} {w : W → List Bool} (hw : Wf clk crn d w) (k : W) (v : List Bool)
    (h1 : w k <+: v) (h2 : v <+: drv clk crn d w k) : Wf clk crn d (upd w k v) := by
  refine Wf_step hw (upd_ge h1) (fun j => ?_); by_cases hj : j = k
  · subst hj; simpa [upd] using h2
  · simp only [upd, if_neg hj]; exact hw j

/-- The reported output only grows, so its clause survives any step.  The one clause that is
about the block's interface rather than its wiring. -/
theorem hq_set {w : W → List Bool} {k v q} (h1 : w k <+: v)
    (hq : q <+: pack3Out (w .pk0) (w .pk1) (w .pk2)) :
    q <+: pack3Out (upd w k v .pk0) (upd w k v .pk1) (upd w k v .pk2) :=
  hq.trans (pack3Out_mono (upd_ge h1 _) (upd_ge h1 _) (upd_ge h1 _))

theorem Wf_init {clk crn d} : Wf clk crn d (fun _ => []) := fun _ => List.nil_prefix

/-! ### The bridge to the reduced module -/

/-- The reduced state is a nested product; `wires` reads it as an assignment. -/
def wires (i : busT) : W → List Bool
  | .pk0 => i.1.1 | .pk1 => i.1.2.1 | .pk2 => i.1.2.2
  | .f0clk => i.2.2.2.2.1.1 | .f0d => i.2.2.2.2.1.2.1 | .f0crn => i.2.2.2.2.1.2.2
  | .f1clk => i.2.2.2.2.2.1.1 | .f1d => i.2.2.2.2.2.1.2.1 | .f1crn => i.2.2.2.2.2.1.2.2
  | .f2clk => i.2.2.2.2.2.2.1 | .f2d => i.2.2.2.2.2.2.2.1 | .f2crn => i.2.2.2.2.2.2.2.2

def psi (i : busT) (s : List Bool × List (BitVec 3) × List Bool × List (BitVec 3)) : Prop :=
  Wf s.1 s.2.2.1 s.2.1 (wires i) ∧ i.2.2.2.1 = s.1 ∧ i.2.1 = s.2.1 ∧ i.2.2.1 = s.2.2.1
    ∧ s.2.2.2 <+: pack3Out (wires i .pk0) (wires i .pk1) (wires i .pk2)

/-! ### One tactic for every connection

Destructure the two states, split the rule, re-establish the invariant: the same text for all
twelve rules.  Only *which* wire advances differs, and that is the argument. -/

syntax "connect_case " term : tactic
set_option hygiene false in
macro_rules
  | `(tactic| connect_case $w:term) => `(tactic| (
      obtain ⟨⟨pk0, pk1, pk2⟩, ud, cr, ck, ⟨a0,a1,a2⟩, ⟨b0,b1,b2⟩, ⟨c0,c1,c2⟩⟩ := i
      obtain ⟨⟨_,_,_⟩, _, _, _, ⟨_,_,_⟩, ⟨_,_,_⟩, ⟨_,_,_⟩⟩ := mid
      have Hr := Hrule.1 rfl; clear Hrule
      obtain ⟨⟨⟨_,_,_⟩,_,_,_,⟨_,_,_⟩,⟨_,_,_⟩,⟨_,_,_⟩⟩, out, Hr⟩ := Hr
      simp only [Prod.mk.injEq, and_assoc] at Hr
      repeat' (obtain ⟨hh, Hr⟩ := Hr; try subst hh)
      obtain ⟨hw, e1, e2, e3, hq⟩ := H
      refine ⟨s, existSR_reflexive, ?_, e1, e2, e3, ?_⟩
      · have key := Wf_set hw $w _ (‹_ ⊏ _›).isPrefix (by
          simp only [drv, wires]
          first
            | exact e1 ▸ List.prefix_rfl
            | exact e3 ▸ List.prefix_rfl
            | exact e2 ▸ List.prefix_rfl
            | assumption)
        intro j; have hj := key j; revert hj; cases j <;> simp [wires, upd, drv]
      · have key := hq_set (k := $w) (‹_ ⊏ _›).isPrefix hq
        revert key; simp [wires, upd]))

/-! All twelve connections, one line each. -/

theorem case_0 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 0 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f0clk

theorem case_1 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 1 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f1clk

theorem case_2 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 2 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f2clk

theorem case_3 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 3 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f0crn

theorem case_4 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 4 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f1crn

theorem case_5 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 5 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f2crn

theorem case_6 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 6 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f0d

theorem case_7 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 7 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f1d

theorem case_8 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 8 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.f2d

theorem case_9 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 9 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.pk0

theorem case_10 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 10 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.pk1

theorem case_11 (s) (i mid : busT) (H : psi i s)
    (Hrule : (busNetlist.internals.getD 11 (fun _ _ => False)) i mid) :
    ∃ s', existSR busSpec.internals s s' ∧ psi mid s' := by connect_case W.pk2

end Graphiti.AsyncFifo.IndexedWf
