/-
Copyright (c) 2026 VCA Lab, EPFL. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Bourgeat, Claude
-/

import Graphiti.Core.Graph.ModuleLemmas
import Graphiti.Core.Graph.ModuleReduction
import Graphiti.Core.Graph.ExprHighElaborator
import Graphiti.Projects.AsyncFifo.Filtered

/-!
# Graphiti modules for the asynchronous FIFO

Following Kobler's translation pattern, every block is a Graphiti module whose state is
the most information received so far on each of its input ports:

* an input rule on port `p` replaces the stored stream by a strictly longer one;
* an output rule emits the block's output stream computed from the stored inputs; a block
  whose output is not a function of its inputs (the filtered domains) also remembers the
  stream it emitted and only ever extends it;
* there are no internal rules; the internal rules of the composed circuit are the wire
  connections generated by Graphiti.

The implementation blocks are the write domain and the read domain, in two versions: the
exact ones (`writeDomain`, `readDomain`, outputs are the streams of `Domains.lean`) and the
filtered ones (`writeDomainF`, `readDomainF`, outputs satisfy the relaxed relations of
`Filtered.lean` with clk-to-q window `kq`, clock filter `P`, input filter `S` and reset
filter `R`).  Both are parametrised by the wire latency `lat`, the settling time `stl` and
the setup window `su` of their synchronisers.  Two *oracle* modules produce arbitrary streams
resolving the metastability of the synchronisers.  The specification is a single module,
parametrised by the clock periods `P_w`, `P_r`, the input setup windows `S_w`, `S_r` and the
reset times `R_w`, `R_r` it assumes, whose state is the eight interface streams and whose
output rules only allow extensions that keep `FifoOK P_w P_r S_w S_r R_w R_r` true.
-/

namespace Graphiti.AsyncFifo

section Components

variable (α : Type) [Inhabited α] (n lat stl su : Nat)

/-- State of the write-domain module: the streams received on `clk`, `inc`, `data`, `rgray`, `orc`. -/
abbrev WState := List Bool × List Bool × List α × List (BitVec (n+1)) × List (Orc n)

@[drcomponents]
def writeDomain : StringModule (WState α n) :=
  { inputs := [ (↑"clk", ⟨List Bool, fun s v s' => s.1 ⊏ v ∧ s' = (v, s.2)⟩)
              , (↑"inc", ⟨List Bool, fun s v s' => s.2.1 ⊏ v ∧ s' = (s.1, v, s.2.2)⟩)
              , (↑"data", ⟨List α, fun s v s' => s.2.2.1 ⊏ v ∧ s' = (s.1, s.2.1, v, s.2.2.2)⟩)
              , (↑"rgray", ⟨List (BitVec (n+1)), fun s v s' => s.2.2.2.1 ⊏ v ∧ s' = (s.1, s.2.1, s.2.2.1, v, s.2.2.2.2)⟩)
              , (↑"orc", ⟨List (Orc n), fun s v s' => s.2.2.2.2 ⊏ v ∧ s' = (s.1, s.2.1, s.2.2.1, s.2.2.2.1, v)⟩)
              ].toAssocList
    outputs := [ (↑"gray", ⟨List (BitVec (n+1)), fun s v s' =>
                    s' = s ∧ v = wGray lat stl su s.1 s.2.1 s.2.2.1 s.2.2.2.1 s.2.2.2.2⟩)
               , (↑"full", ⟨List Bool, fun s v s' =>
                    s' = s ∧ v = wFull lat stl su s.1 s.2.1 s.2.2.1 s.2.2.2.1 s.2.2.2.2⟩)
               , (↑"mem", ⟨List (BitVec n → α), fun s v s' =>
                    s' = s ∧ v = wMem lat stl su s.1 s.2.1 s.2.2.1 s.2.2.2.1 s.2.2.2.2⟩)
               ].toAssocList
    internals := []
    init_state := fun s => s = ([], [], [], [], []) }

/-- State of the read-domain module: the streams received on `clk`, `inc`, `wgray`, `orc`, `mem`. -/
abbrev RState := List Bool × List Bool × List (BitVec (n+1)) × List (Orc n) × List (BitVec n → α)

@[drcomponents]
def readDomain : StringModule (RState α n) :=
  { inputs := [ (↑"clk", ⟨List Bool, fun s v s' => s.1 ⊏ v ∧ s' = (v, s.2)⟩)
              , (↑"inc", ⟨List Bool, fun s v s' => s.2.1 ⊏ v ∧ s' = (s.1, v, s.2.2)⟩)
              , (↑"wgray", ⟨List (BitVec (n+1)), fun s v s' => s.2.2.1 ⊏ v ∧ s' = (s.1, s.2.1, v, s.2.2.2)⟩)
              , (↑"orc", ⟨List (Orc n), fun s v s' => s.2.2.2.1 ⊏ v ∧ s' = (s.1, s.2.1, s.2.2.1, v, s.2.2.2.2)⟩)
              , (↑"mem", ⟨List (BitVec n → α), fun s v s' => s.2.2.2.2 ⊏ v ∧ s' = (s.1, s.2.1, s.2.2.1, s.2.2.2.1, v)⟩)
              ].toAssocList
    outputs := [ (↑"gray", ⟨List (BitVec (n+1)), fun s v s' =>
                    s' = s ∧ v = rGray lat stl su s.1 s.2.1 s.2.2.1 s.2.2.2.1⟩)
               , (↑"empty", ⟨List Bool, fun s v s' =>
                    s' = s ∧ v = rEmpty lat stl su s.1 s.2.1 s.2.2.1 s.2.2.2.1⟩)
               , (↑"rdata", ⟨List α, fun s v s' =>
                    s' = s ∧ v = rData lat stl su s.1 s.2.1 s.2.2.1 s.2.2.2.1 s.2.2.2.2⟩)
               ].toAssocList
    internals := []
    init_state := fun s => s = ([], [], [], [], []) }

/-- State of the filtered write-domain module: the five input streams and the three output
streams emitted so far. -/
structure WStateF (α : Type) (n : Nat) where
  clk : List Bool
  inc : List Bool
  data : List α
  rgray : List (BitVec (n+1))
  orc : List (Orc n)
  gray_q : List (BitVec (n+1))
  full_q : List Bool
  mem_q : List (BitVec n → α)

/-- The write domain with its timing assumptions as filters: the outputs are only determined
outside clk-to-q windows (`kq`) and while the clock (`P`) and the inputs (`S`) respect their
assumptions; an output may only be extended. -/
@[drcomponents]
def writeDomainF (kq P S R pw : Nat) : StringModule (WStateF α n) :=
  { inputs := [ (↑"clk", ⟨List Bool, fun s v s' => s.clk ⊏ v ∧ s' = { s with clk := v }⟩)
              , (↑"inc", ⟨List Bool, fun s v s' => s.inc ⊏ v ∧ s' = { s with inc := v }⟩)
              , (↑"data", ⟨List α, fun s v s' => s.data ⊏ v ∧ s' = { s with data := v }⟩)
              , (↑"rgray", ⟨List (BitVec (n+1)), fun s v s' => s.rgray ⊏ v ∧ s' = { s with rgray := v }⟩)
              , (↑"orc", ⟨List (Orc n), fun s v s' => s.orc ⊏ v ∧ s' = { s with orc := v }⟩)
              ].toAssocList
    outputs := [ (↑"gray", ⟨List (BitVec (n+1)), fun s v s' => s.gray_q <+: v ∧
                    WGrayF lat stl su kq P S R pw s.clk s.inc s.data s.rgray s.orc v ∧ s' = { s with gray_q := v }⟩)
               , (↑"full", ⟨List Bool, fun s v s' => s.full_q <+: v ∧
                    WFullF lat stl su kq P S R pw s.clk s.inc s.data s.rgray s.orc v ∧ s' = { s with full_q := v }⟩)
               , (↑"mem", ⟨List (BitVec n → α), fun s v s' => s.mem_q <+: v ∧
                    WMemF lat stl su kq P S R pw s.clk s.inc s.data s.rgray s.orc v ∧ s' = { s with mem_q := v }⟩)
               ].toAssocList
    internals := []
    init_state := fun s => s = ⟨[], [], [], [], [], [], [], []⟩ }

structure RStateF (α : Type) (n : Nat) where
  clk : List Bool
  inc : List Bool
  wgray : List (BitVec (n+1))
  orc : List (Orc n)
  mem : List (BitVec n → α)
  gray_q : List (BitVec (n+1))
  empty_q : List Bool
  rdata_q : List α

@[drcomponents]
def readDomainF (kq rdly P S R pw : Nat) : StringModule (RStateF α n) :=
  { inputs := [ (↑"clk", ⟨List Bool, fun s v s' => s.clk ⊏ v ∧ s' = { s with clk := v }⟩)
              , (↑"inc", ⟨List Bool, fun s v s' => s.inc ⊏ v ∧ s' = { s with inc := v }⟩)
              , (↑"wgray", ⟨List (BitVec (n+1)), fun s v s' => s.wgray ⊏ v ∧ s' = { s with wgray := v }⟩)
              , (↑"orc", ⟨List (Orc n), fun s v s' => s.orc ⊏ v ∧ s' = { s with orc := v }⟩)
              , (↑"mem", ⟨List (BitVec n → α), fun s v s' => s.mem ⊏ v ∧ s' = { s with mem := v }⟩)
              ].toAssocList
    outputs := [ (↑"gray", ⟨List (BitVec (n+1)), fun s v s' => s.gray_q <+: v ∧
                    RGrayF lat stl su kq P S R pw s.clk s.inc s.wgray s.orc v ∧ s' = { s with gray_q := v }⟩)
               , (↑"empty", ⟨List Bool, fun s v s' => s.empty_q <+: v ∧
                    REmptyF lat stl su kq P S R pw s.clk s.inc s.wgray s.orc v ∧ s' = { s with empty_q := v }⟩)
               , (↑"rdata", ⟨List α, fun s v s' => s.rdata_q <+: v ∧
                    RDataF lat stl su kq rdly P S R pw s.clk s.inc s.wgray s.orc s.mem v ∧ s' = { s with rdata_q := v }⟩)
               ].toAssocList
    internals := []
    init_state := fun s => s = ⟨[], [], [], [], [], [], [], []⟩ }

/-- An oracle: a source of arbitrary streams, used to make the metastability resolution of a
synchroniser an explicit (adversarial) input of the circuit. -/
@[drcomponents]
def oracle : StringModule Unit :=
  { inputs := ∅
    outputs := [ (↑"bits", ⟨List (Orc n), fun s _ s' => s' = s⟩) ].toAssocList
    internals := []
    init_state := fun _ => True }

/-- **The specification module.**  Its state records the inputs received and the outputs
committed so far; an output may be extended (non-strictly) as long as `FifoOK P_w P_r S_w S_r R_w R_r`
keeps holding for the committed streams, i.e. the FIFO property holds at every instant up to
which both clocks have respected their assumed minimum periods and the synchronous inputs
their setup windows. -/
def fifoSpec (P_w P_r S_w S_r R_w R_r pw_w pw_r : Nat) : StringModule (FifoIO α) :=
  { inputs := [ (↑"wclk", ⟨List Bool, fun s v s' => s.wclk ⊏ v ∧ s' = { s with wclk := v }⟩)
              , (↑"winc", ⟨List Bool, fun s v s' => s.winc ⊏ v ∧ s' = { s with winc := v }⟩)
              , (↑"wdata", ⟨List α, fun s v s' => s.wdata ⊏ v ∧ s' = { s with wdata := v }⟩)
              , (↑"rclk", ⟨List Bool, fun s v s' => s.rclk ⊏ v ∧ s' = { s with rclk := v }⟩)
              , (↑"rinc", ⟨List Bool, fun s v s' => s.rinc ⊏ v ∧ s' = { s with rinc := v }⟩)
              ].toAssocList
    outputs := [ (↑"full", ⟨List Bool, fun s v s' =>
                    s.full <+: v ∧ FifoOK P_w P_r S_w S_r R_w R_r pw_w pw_r { s with full := v } ∧ s' = { s with full := v }⟩)
               , (↑"empty", ⟨List Bool, fun s v s' =>
                    s.empty <+: v ∧ FifoOK P_w P_r S_w S_r R_w R_r pw_w pw_r { s with empty := v } ∧ s' = { s with empty := v }⟩)
               , (↑"rdata", ⟨List α, fun s v s' =>
                    s.rdata <+: v ∧ FifoOK P_w P_r S_w S_r R_w R_r pw_w pw_r { s with rdata := v } ∧ s' = { s with rdata := v }⟩)
               ].toAssocList
    internals := []
    init_state := fun s => s = FifoIO.empty_io }

end Components

section Circuit

variable (α : Type) [Inhabited α] (n lat stl su : Nat)

/-- The asynchronous FIFO as a Graphiti graph. -/
def asyncFifoGraph := [graphEnv|
    wclk [type="io"];
    winc [type="io"];
    wdata [type="io"];
    rclk [type="io"];
    rinc [type="io"];
    full [type="io"];
    empty [type="io"];
    rdata [type="io"];

    wdom [type="wdom", typeImp=$(⟨_, writeDomain α n lat stl su⟩)];
    rdom [type="rdom", typeImp=$(⟨_, readDomain α n lat stl su⟩)];
    orcw [type="oracle_w", typeImp=$(⟨_, oracle n⟩)];
    orcr [type="oracle_r", typeImp=$(⟨_, oracle n⟩)];

    wclk -> wdom [to="clk"];
    winc -> wdom [to="inc"];
    wdata -> wdom [to="data"];
    rclk -> rdom [to="clk"];
    rinc -> rdom [to="inc"];

    wdom -> rdom [from="gray", to="wgray"];
    rdom -> wdom [from="gray", to="rgray"];
    wdom -> rdom [from="mem", to="mem"];
    orcw -> wdom [from="bits", to="orc"];
    orcr -> rdom [from="bits", to="orc"];

    wdom -> full [from="full"];
    rdom -> empty [from="empty"];
    rdom -> rdata [from="rdata"];
  ]

/-- The lowered graph (topology only, independent of the parameters). -/
@[drunfold_defs]
def asyncFifoLowered := (asyncFifoGraph Unit 0 0 0 0).1.lower_TR |>.get rfl

def env := (asyncFifoGraph α n lat stl su).2

@[drenv] theorem env_wdom : (env α n lat stl su).find? "wdom" = .some ⟨_, writeDomain α n lat stl su⟩ := rfl
@[drenv] theorem env_rdom : (env α n lat stl su).find? "rdom" = .some ⟨_, readDomain α n lat stl su⟩ := rfl
@[drenv] theorem env_orcw : (env α n lat stl su).find? "oracle_w" = .some ⟨_, oracle n⟩ := rfl
@[drenv] theorem env_orcr : (env α n lat stl su).find? "oracle_r" = .some ⟨_, oracle n⟩ := rfl

/-! ### The same circuit over the filtered domains -/

variable (kq rdly P_w P_r S_w S_r R_w R_r pw_w pw_r : Nat)

def asyncFifoGraphF := [graphEnv|
    wclk [type="io"];
    winc [type="io"];
    wdata [type="io"];
    rclk [type="io"];
    rinc [type="io"];
    full [type="io"];
    empty [type="io"];
    rdata [type="io"];

    wdom [type="wdom", typeImp=$(⟨_, writeDomainF α n lat stl su kq P_w S_w R_w pw_w⟩)];
    rdom [type="rdom", typeImp=$(⟨_, readDomainF α n lat stl su kq rdly P_r S_r R_r pw_r⟩)];
    orcw [type="oracle_w", typeImp=$(⟨_, oracle n⟩)];
    orcr [type="oracle_r", typeImp=$(⟨_, oracle n⟩)];

    wclk -> wdom [to="clk"];
    winc -> wdom [to="inc"];
    wdata -> wdom [to="data"];
    rclk -> rdom [to="clk"];
    rinc -> rdom [to="inc"];

    wdom -> rdom [from="gray", to="wgray"];
    rdom -> wdom [from="gray", to="rgray"];
    wdom -> rdom [from="mem", to="mem"];
    orcw -> wdom [from="bits", to="orc"];
    orcr -> rdom [from="bits", to="orc"];

    wdom -> full [from="full"];
    rdom -> empty [from="empty"];
    rdom -> rdata [from="rdata"];
  ]

/-- The topology is the same as `asyncFifoGraph`'s: only the environment changes. -/
theorem asyncFifoGraphF_lower : (asyncFifoGraphF Unit 0 0 0 0 0 0 0 0 0 0 0 0 0 0).1.lower_TR = (asyncFifoGraph Unit 0 0 0 0).1.lower_TR := rfl

def envF := (asyncFifoGraphF α n lat stl su kq rdly P_w P_r S_w S_r R_w R_r pw_w pw_r).2

@[drenv] theorem envF_wdom : (envF α n lat stl su kq rdly P_w P_r S_w S_r R_w R_r pw_w pw_r).find? "wdom" =
  .some ⟨_, writeDomainF α n lat stl su kq P_w S_w R_w pw_w⟩ := rfl
@[drenv] theorem envF_rdom : (envF α n lat stl su kq rdly P_w P_r S_w S_r R_w R_r pw_w pw_r).find? "rdom" =
  .some ⟨_, readDomainF α n lat stl su kq rdly P_r S_r R_r pw_r⟩ := rfl
@[drenv] theorem envF_orcw : (envF α n lat stl su kq rdly P_w P_r S_w S_r R_w R_r pw_w pw_r).find? "oracle_w" = .some ⟨_, oracle n⟩ := rfl
@[drenv] theorem envF_orcr : (envF α n lat stl su kq rdly P_w P_r S_w S_r R_w R_r pw_w pw_r).find? "oracle_r" = .some ⟨_, oracle n⟩ := rfl

abbrev asyncFifoFT : Type := Unit × RStateF α n × WStateF α n × Unit

seal envF in
def_module asyncFifoFT' : Type :=
  [T| asyncFifoLowered, (envF α n lat stl su kq rdly P_w P_r S_w S_r R_w R_r pw_w pw_r).find? ]
reduction_by
  dsimp -failIfUnchanged [drunfold_defs, toString, reduceAssocListfind?, reduceListPartition]
  dsimp -failIfUnchanged [reduceExprHighLower, reduceExprHighLowerProdTR, reduceExprHighLowerConnTR]
  dsimp [ExprHigh.uncurry, ExprLow.build_module_expr, ExprLow.build_module_type,
         ExprLow.build_module, ExprLow.build_module', toString]
  simp only [drenv]
  dsimp

/-- A compiled check, not a step of any proof: the type `def_module` reduces the graph to
is the one written by hand above, so the hand-written `abbrev` — which every statement below
names — cannot drift from the graph. -/
theorem asyncFifoFT_eq : asyncFifoFT' α n = asyncFifoFT α n := rfl

seal envF in
def_module asyncFifoF : StringModule (asyncFifoFT α n) :=
  [e| asyncFifoLowered, (envF α n lat stl su kq rdly P_w P_r S_w S_r R_w R_r pw_w pw_r).find? ]

end Circuit

end Graphiti.AsyncFifo
