/-
Copyright (c) 2026 VCA Lab, EPFL. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Bourgeat, Claude
-/

import Graphiti.Projects.AsyncFifo.BusRegTiming

/-!
# The two-flip-flop synchroniser

The Gray pointer arriving from the other clock domain is sampled by two registers in series:
the first may be sampling a bus that is changing, the second re-samples what the first settled
on.  Both are the three-bit register of `BusReg.lean`, so as a netlist this is only wiring.

What this file does *not* do is relate the netlist to `Timed.syncReg`, and that is not an
omission.  `Timed.syncReg` reads an oracle -- which bits of a metastable sample resolve to the
new value, and what is observed while the first stage settles -- and one might hope the netlist
could discharge the oracle by reading it off its own behaviour.  It cannot, and not for want of
trying: `Metastability.lean` exhibits a run with a clean clock, a released clear and data
glitching inside the aperture for which the netlist oscillates for ever, so there is no instant
after which its output is the value at the edge, the value before the aperture, or any other
constant -- nothing an oracle can name.  `syncNetlist ⊑ Timed.syncReg` is therefore false, and
what is at fault is the model: a deterministic Boolean model has no noise to knock a bistable
off its balance point and no continuum for it to slide down, while a real stage resolves after
a random time with an exponentially decaying tail.  That is an MTBF argument, so the settling
of the first stage stays an assumption -- `Timed.syncReg` and `stl < P` are where it is
written down.  This file is still the honest account of the *wiring*: two `BusReg` stages in
series, `syncGateOut`, and the second stage, whose data is stable from `stl` instants after an
edge, is an ordinary register of the bank.
-/

set_option linter.unusedSectionVars false
set_option linter.unusedSimpArgs false

namespace Graphiti.AsyncFifo.Sync

open Graphiti.AsyncFifo Graphiti.AsyncFifo.Gates Graphiti.AsyncFifo.Timed Graphiti.AsyncFifo.BusReg

/-- What the two stages report: the second register over the first's output. -/
def syncGateOut (clk : List Bool) (d : List (BitVec 3)) (crn : List Bool) : List (BitVec 3) :=
  busOut clk (busOut clk d crn) crn

theorem syncGateOut_mono {clk clk' : List Bool} {d d' : List (BitVec 3)} {crn crn' : List Bool}
    (hc : clk <+: clk') (hd : d <+: d') (hr : crn <+: crn') :
    syncGateOut clk d crn <+: syncGateOut clk' d' crn' :=
  busOut_mono hc (busOut_mono hc hd hr) hr

/-! ### The netlist -/

def syncGraph := [graphEnv|
    clk [type="io"];
    d [type="io"];
    clrn [type="io"];
    q [type="io"];

    clkF [type="fork2", typeImp=$(⟨_, Timed.fork2 Bool⟩)];
    crF [type="fork2", typeImp=$(⟨_, Timed.fork2 Bool⟩)];
    s1 [type="busreg", typeImp=$(⟨_, busSpec⟩)];
    s2 [type="busreg", typeImp=$(⟨_, busSpec⟩)];

    clk -> clkF [to="in"];
    d -> s1 [to="d"];
    clrn -> crF [to="in"];

    clkF -> s1 [from="out1", to="clk"];
    clkF -> s2 [from="out2", to="clk"];
    crF -> s1 [from="out1", to="clrn"];
    crF -> s2 [from="out2", to="clrn"];
    s1 -> s2 [from="q", to="d"];

    s2 -> q [from="q"];
  ]

@[drunfold_defs]
def syncLowered := syncGraph.1.lower_TR |>.get rfl

def yenv := syncGraph.2

@[drenv] theorem yenv_fork2 : yenv.find? "fork2" = .some ⟨_, Timed.fork2 Bool⟩ := rfl
@[drenv] theorem yenv_busreg : yenv.find? "busreg" = .some ⟨_, busSpec⟩ := rfl

seal yenv in
def_module syncT : Type :=
  [T| syncLowered, yenv.find? ]
reduction_by
  dsimp -failIfUnchanged [drunfold_defs, toString, reduceAssocListfind?, reduceListPartition]
  dsimp -failIfUnchanged [reduceExprHighLower, reduceExprHighLowerProdTR, reduceExprHighLowerConnTR]
  dsimp [ExprHigh.uncurry, ExprLow.build_module_expr, ExprLow.build_module_type,
         ExprLow.build_module, ExprLow.build_module', toString]
  simp only [drenv]
  dsimp

seal yenv in
def_module syncNetlist : StringModule syncT :=
  [e| syncLowered, yenv.find? ]

-- HEADER_END (everything below is generated by gen/gen_sync.py)

/-! ### The specification -/

/-- The synchroniser as a single block. -/
@[drcomponents]
def syncSpec : StringModule (List Bool × List (BitVec 3) × List Bool × List (BitVec 3)) :=
  { inputs := [ (↑"clk", ⟨List Bool, fun s v s' => s.1 ⊏ v ∧ s' = (v, s.2)⟩)
              , (↑"d", ⟨List (BitVec 3), fun s v s' => s.2.1 ⊏ v ∧ s' = (s.1, v, s.2.2)⟩)
              , (↑"clrn", ⟨List Bool, fun s v s' => s.2.2.1 ⊏ v ∧ s' = (s.1, s.2.1, v, s.2.2.2)⟩)
              ].toAssocList
    outputs := [ (↑"q", ⟨List (BitVec 3), fun s v s' => s.2.2.2 <+: v ∧
                    v <+: syncGateOut s.1 s.2.1 s.2.2.1 ∧ s' = (s.1, s.2.1, s.2.2.1, v)⟩) ].toAssocList
    internals := []
    init_state := fun s => s = ([], [], [], []) }

instance : MatchInterface syncNetlist syncSpec := by
  dsimp [syncNetlist, syncSpec]
  solve_match_interface

/-! ### The invariant -/

structure Wf (crF_in : List Bool) (s2_clk : List Bool) (s2_d : List (BitVec 3)) (s2_clrn : List Bool) (s2_qh : List (BitVec 3)) (clkF_in : List Bool) (s1_clk : List Bool) (s1_d : List (BitVec 3)) (s1_clrn : List Bool) (s : List Bool × List (BitVec 3) × List Bool × List (BitVec 3)) : Prop where
  e_clk : clkF_in = s.1
  e_d : s1_d = s.2.1
  e_crn : crF_in = s.2.2.1
  e_qh : s2_qh = s.2.2.2
  w_s2_clk : s2_clk <+: clkF_in
  w_s2_d : s2_d <+: busOut s1_clk s1_d s1_clrn
  w_s2_clrn : s2_clrn <+: crF_in
  w_s1_clk : s1_clk <+: clkF_in
  w_s1_clrn : s1_clrn <+: crF_in

def ψ (i : syncT) (s : List Bool × List (BitVec 3) × List Bool × List (BitVec 3)) : Prop :=
  Wf i.1 i.2.1.1 i.2.1.2.1 i.2.1.2.2.1 i.2.1.2.2.2 i.2.2.1 i.2.2.2.1 i.2.2.2.2.1 i.2.2.2.2.2.1 s

theorem Wf.init : Wf [] [] [] [] [] [] [] [] [] ([], [], [], []) :=
  ⟨rfl, rfl, rfl, rfl, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix, List.nil_prefix⟩

section SpecRules
variable (sp : List Bool × List (BitVec 3) × List Bool × List (BitVec 3))

theorem spec_in_clk (v : List Bool) (h : sp.1 ⊏ v) :
    (syncSpec.inputs.getIO ↑"clk").2 sp v (v, sp.2) := by
  rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])]; exact ⟨h, rfl⟩

theorem spec_in_d (v : List (BitVec 3)) (h : sp.2.1 ⊏ v) :
    (syncSpec.inputs.getIO ↑"d").2 sp v (sp.1, v, sp.2.2) := by
  rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])]; exact ⟨h, rfl⟩

theorem spec_in_clrn (v : List Bool) (h : sp.2.2.1 ⊏ v) :
    (syncSpec.inputs.getIO ↑"clrn").2 sp v (sp.1, sp.2.1, v, sp.2.2.2) := by
  rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])]; exact ⟨h, rfl⟩

theorem spec_out_q (v : List (BitVec 3)) (h1 : sp.2.2.2 <+: v) (h2 : v <+: syncGateOut sp.1 sp.2.1 sp.2.2.1) :
    (syncSpec.outputs.getIO ↑"q").2 sp v (sp.1, sp.2.1, sp.2.2.1, v) := by
  rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])]; exact ⟨h1, h2, rfl⟩

end SpecRules

section Cases
variable {crF_in : List Bool} {s2_clk : List Bool} {s2_d : List (BitVec 3)} {s2_clrn : List Bool} {s2_qh : List (BitVec 3)} {clkF_in : List Bool} {s1_clk : List Bool} {s1_d : List (BitVec 3)} {s1_clrn : List Bool} {sp : List Bool × List (BitVec 3) × List Bool × List (BitVec 3)}
  (Hψ : Wf crF_in s2_clk s2_d s2_clrn s2_qh clkF_in s1_clk s1_d s1_clrn sp)
include Hψ

theorem in_clk (v : List Bool) (h : clkF_in ⊏ v) :
    Wf crF_in s2_clk s2_d s2_clrn s2_qh (v) s1_clk s1_d s1_clrn (v, sp.2) := by
  have hm : clkF_in <+: v := h.isPrefix
  exact { e_clk := rfl
          e_d := Hψ.e_d
          e_crn := Hψ.e_crn
          e_qh := Hψ.e_qh
          w_s2_clk := Hψ.w_s2_clk.trans hm
          w_s2_d := Hψ.w_s2_d
          w_s2_clrn := Hψ.w_s2_clrn
          w_s1_clk := Hψ.w_s1_clk.trans hm
          w_s1_clrn := Hψ.w_s1_clrn }

theorem in_d (v : List (BitVec 3)) (h : s1_d ⊏ v) :
    Wf crF_in s2_clk s2_d s2_clrn s2_qh clkF_in s1_clk (v) s1_clrn (sp.1, v, sp.2.2) := by
  have hm : s1_d <+: v := h.isPrefix
  exact { e_clk := Hψ.e_clk
          e_d := rfl
          e_crn := Hψ.e_crn
          e_qh := Hψ.e_qh
          w_s2_clk := Hψ.w_s2_clk
          w_s2_d := Hψ.w_s2_d.trans (busOut_mono List.prefix_rfl hm List.prefix_rfl)
          w_s2_clrn := Hψ.w_s2_clrn
          w_s1_clk := Hψ.w_s1_clk
          w_s1_clrn := Hψ.w_s1_clrn }

theorem in_clrn (v : List Bool) (h : crF_in ⊏ v) :
    Wf (v) s2_clk s2_d s2_clrn s2_qh clkF_in s1_clk s1_d s1_clrn (sp.1, sp.2.1, v, sp.2.2.2) := by
  have hm : crF_in <+: v := h.isPrefix
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_crn := rfl
          e_qh := Hψ.e_qh
          w_s2_clk := Hψ.w_s2_clk
          w_s2_d := Hψ.w_s2_d
          w_s2_clrn := Hψ.w_s2_clrn.trans hm
          w_s1_clk := Hψ.w_s1_clk
          w_s1_clrn := Hψ.w_s1_clrn.trans hm }

theorem int_0 (_h : s1_clk ⊏ clkF_in) :
    Wf crF_in s2_clk s2_d s2_clrn s2_qh clkF_in (clkF_in) s1_d s1_clrn sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_crn := Hψ.e_crn
          e_qh := Hψ.e_qh
          w_s2_clk := Hψ.w_s2_clk
          w_s2_d := Hψ.w_s2_d.trans (busOut_mono Hψ.w_s1_clk List.prefix_rfl List.prefix_rfl)
          w_s2_clrn := Hψ.w_s2_clrn
          w_s1_clk := List.prefix_rfl
          w_s1_clrn := Hψ.w_s1_clrn }

theorem int_1 (_h : s2_clk ⊏ clkF_in) :
    Wf crF_in (clkF_in) s2_d s2_clrn s2_qh clkF_in s1_clk s1_d s1_clrn sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_crn := Hψ.e_crn
          e_qh := Hψ.e_qh
          w_s2_clk := List.prefix_rfl
          w_s2_d := Hψ.w_s2_d
          w_s2_clrn := Hψ.w_s2_clrn
          w_s1_clk := Hψ.w_s1_clk
          w_s1_clrn := Hψ.w_s1_clrn }

theorem int_2 (_h : s1_clrn ⊏ crF_in) :
    Wf crF_in s2_clk s2_d s2_clrn s2_qh clkF_in s1_clk s1_d (crF_in) sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_crn := Hψ.e_crn
          e_qh := Hψ.e_qh
          w_s2_clk := Hψ.w_s2_clk
          w_s2_d := Hψ.w_s2_d.trans (busOut_mono List.prefix_rfl List.prefix_rfl Hψ.w_s1_clrn)
          w_s2_clrn := Hψ.w_s2_clrn
          w_s1_clk := Hψ.w_s1_clk
          w_s1_clrn := List.prefix_rfl }

theorem int_3 (_h : s2_clrn ⊏ crF_in) :
    Wf crF_in s2_clk s2_d (crF_in) s2_qh clkF_in s1_clk s1_d s1_clrn sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_crn := Hψ.e_crn
          e_qh := Hψ.e_qh
          w_s2_clk := Hψ.w_s2_clk
          w_s2_d := Hψ.w_s2_d
          w_s2_clrn := List.prefix_rfl
          w_s1_clk := Hψ.w_s1_clk
          w_s1_clrn := Hψ.w_s1_clrn }

theorem int_4 {out : List (BitVec 3)} (_h : s2_d ⊏ out) (hout : out <+: busOut s1_clk s1_d s1_clrn) :
    Wf crF_in s2_clk (out) s2_clrn s2_qh clkF_in s1_clk s1_d s1_clrn sp := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_crn := Hψ.e_crn
          e_qh := Hψ.e_qh
          w_s2_clk := Hψ.w_s2_clk
          w_s2_d := hout
          w_s2_clrn := Hψ.w_s2_clrn
          w_s1_clk := Hψ.w_s1_clk
          w_s1_clrn := Hψ.w_s1_clrn }

/-- The second stage sees a prefix of the first stage's output, over prefixes of the
block's own clock and clear. -/
theorem out_q {v : List (BitVec 3)} (h : v <+: busOut s2_clk s2_d s2_clrn) :
    v <+: syncGateOut sp.1 sp.2.1 sp.2.2.1 :=
  h.trans (busOut_mono (Hψ.w_s2_clk.trans (Hψ.e_clk ▸ List.prefix_rfl))
    (Hψ.w_s2_d.trans (busOut_mono (Hψ.w_s1_clk.trans (Hψ.e_clk ▸ List.prefix_rfl))
      (Hψ.e_d ▸ List.prefix_rfl) (Hψ.w_s1_clrn.trans (Hψ.e_crn ▸ List.prefix_rfl))))
    (Hψ.w_s2_clrn.trans (Hψ.e_crn ▸ List.prefix_rfl)))


/-- What it has reported it has reported: the second stage records it. -/
theorem out_wf {v : List (BitVec 3)} :
    Wf crF_in s2_clk s2_d s2_clrn (v) clkF_in s1_clk s1_d s1_clrn (sp.1, sp.2.1, sp.2.2.1, v) := by
  exact { e_clk := Hψ.e_clk
          e_d := Hψ.e_d
          e_crn := Hψ.e_crn
          e_qh := rfl
          w_s2_clk := Hψ.w_s2_clk
          w_s2_d := Hψ.w_s2_d
          w_s2_clrn := Hψ.w_s2_clrn
          w_s1_clk := Hψ.w_s1_clk
          w_s1_clrn := Hψ.w_s1_clrn }

end Cases

/-! ### The refinement -/

theorem int_case_0 (s : List Bool × List (BitVec 3) × List Bool × List (BitVec 3)) (i mid : syncT) (Hψ : ψ i s)
    (Hrule : (syncNetlist.internals.getD 0 (fun _ _ => False)) i mid) :
    ∃ s', existSR syncSpec.internals s s' ∧ ψ mid s' := by
  obtain ⟨crF_in, ⟨s2_clk, s2_d, s2_clrn, s2_qh⟩, clkF_in, ⟨s1_clk, s1_d, s1_clrn, s1_qh⟩⟩ := i
  obtain ⟨m_crF_in, ⟨m_s2_clk, m_s2_d, m_s2_clrn, m_s2_qh⟩, m_clkF_in, ⟨m_s1_clk, m_s1_d, m_s1_clrn, m_s1_qh⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨c_crF_in, ⟨c_s2_clk, c_s2_d, c_s2_clrn, c_s2_qh⟩, c_clkF_in, ⟨c_s1_clk, c_s1_d, c_s1_clrn, c_s1_qh⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_0 Hψ ‹_›⟩

theorem int_case_1 (s : List Bool × List (BitVec 3) × List Bool × List (BitVec 3)) (i mid : syncT) (Hψ : ψ i s)
    (Hrule : (syncNetlist.internals.getD 1 (fun _ _ => False)) i mid) :
    ∃ s', existSR syncSpec.internals s s' ∧ ψ mid s' := by
  obtain ⟨crF_in, ⟨s2_clk, s2_d, s2_clrn, s2_qh⟩, clkF_in, ⟨s1_clk, s1_d, s1_clrn, s1_qh⟩⟩ := i
  obtain ⟨m_crF_in, ⟨m_s2_clk, m_s2_d, m_s2_clrn, m_s2_qh⟩, m_clkF_in, ⟨m_s1_clk, m_s1_d, m_s1_clrn, m_s1_qh⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨c_crF_in, ⟨c_s2_clk, c_s2_d, c_s2_clrn, c_s2_qh⟩, c_clkF_in, ⟨c_s1_clk, c_s1_d, c_s1_clrn, c_s1_qh⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_1 Hψ ‹_›⟩

theorem int_case_2 (s : List Bool × List (BitVec 3) × List Bool × List (BitVec 3)) (i mid : syncT) (Hψ : ψ i s)
    (Hrule : (syncNetlist.internals.getD 2 (fun _ _ => False)) i mid) :
    ∃ s', existSR syncSpec.internals s s' ∧ ψ mid s' := by
  obtain ⟨crF_in, ⟨s2_clk, s2_d, s2_clrn, s2_qh⟩, clkF_in, ⟨s1_clk, s1_d, s1_clrn, s1_qh⟩⟩ := i
  obtain ⟨m_crF_in, ⟨m_s2_clk, m_s2_d, m_s2_clrn, m_s2_qh⟩, m_clkF_in, ⟨m_s1_clk, m_s1_d, m_s1_clrn, m_s1_qh⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨c_crF_in, ⟨c_s2_clk, c_s2_d, c_s2_clrn, c_s2_qh⟩, c_clkF_in, ⟨c_s1_clk, c_s1_d, c_s1_clrn, c_s1_qh⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_2 Hψ ‹_›⟩

theorem int_case_3 (s : List Bool × List (BitVec 3) × List Bool × List (BitVec 3)) (i mid : syncT) (Hψ : ψ i s)
    (Hrule : (syncNetlist.internals.getD 3 (fun _ _ => False)) i mid) :
    ∃ s', existSR syncSpec.internals s s' ∧ ψ mid s' := by
  obtain ⟨crF_in, ⟨s2_clk, s2_d, s2_clrn, s2_qh⟩, clkF_in, ⟨s1_clk, s1_d, s1_clrn, s1_qh⟩⟩ := i
  obtain ⟨m_crF_in, ⟨m_s2_clk, m_s2_d, m_s2_clrn, m_s2_qh⟩, m_clkF_in, ⟨m_s1_clk, m_s1_d, m_s1_clrn, m_s1_qh⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨c_crF_in, ⟨c_s2_clk, c_s2_d, c_s2_clrn, c_s2_qh⟩, c_clkF_in, ⟨c_s1_clk, c_s1_d, c_s1_clrn, c_s1_qh⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_3 Hψ ‹_›⟩

theorem int_case_4 (s : List Bool × List (BitVec 3) × List Bool × List (BitVec 3)) (i mid : syncT) (Hψ : ψ i s)
    (Hrule : (syncNetlist.internals.getD 4 (fun _ _ => False)) i mid) :
    ∃ s', existSR syncSpec.internals s s' ∧ ψ mid s' := by
  obtain ⟨crF_in, ⟨s2_clk, s2_d, s2_clrn, s2_qh⟩, clkF_in, ⟨s1_clk, s1_d, s1_clrn, s1_qh⟩⟩ := i
  obtain ⟨m_crF_in, ⟨m_s2_clk, m_s2_d, m_s2_clrn, m_s2_qh⟩, m_clkF_in, ⟨m_s1_clk, m_s1_d, m_s1_clrn, m_s1_qh⟩⟩ := mid
  dsimp only [ψ] at Hψ ⊢
  have H := Hrule.1 rfl
  clear Hrule
  obtain ⟨⟨c_crF_in, ⟨c_s2_clk, c_s2_d, c_s2_clrn, c_s2_qh⟩, c_clkF_in, ⟨c_s1_clk, c_s1_d, c_s1_clrn, c_s1_qh⟩⟩, out, Hrule⟩ := H
  simp only [Prod.mk.injEq, and_assoc, and_true, true_and] at Hrule
  repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
  exact ⟨s, existSR_reflexive, int_4 Hψ ‹_› ‹_›⟩

theorem syncNetlist_internals_eq : syncNetlist.internals = [syncNetlist.internals.getD 0 (fun _ _ => False), syncNetlist.internals.getD 1 (fun _ _ => False), syncNetlist.internals.getD 2 (fun _ _ => False), syncNetlist.internals.getD 3 (fun _ _ => False), syncNetlist.internals.getD 4 (fun _ _ => False)] := rfl

theorem refines_ψ : syncNetlist ⊑_{ψ} syncSpec := by
  intro i s Hψ
  constructor
  · intro ident mid_i v Hrule
    obtain ⟨crF_in, ⟨s2_clk, s2_d, s2_clrn, s2_qh⟩, clkF_in, ⟨s1_clk, s1_d, s1_clrn, s1_qh⟩⟩ := i
    dsimp only [ψ] at Hψ
    obtain ⟨m_crF_in, ⟨m_s2_clk, m_s2_d, m_s2_clrn, m_s2_qh⟩, m_clkF_in, ⟨m_s1_clk, m_s1_d, m_s1_clrn, m_s1_qh⟩⟩ := mid_i
    case_transition Hcontains : Module.inputs syncNetlist, ident, (PortMap.getIO_not_contained_false' Hrule)
    dsimp only [syncNetlist] at Hcontains
    simp at Hcontains
    rcases Hcontains with h | h | h
    all_goals subst h
    all_goals rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])] at Hrule
    all_goals dsimp only at Hrule
    all_goals simp only [Prod.mk.injEq, and_assoc] at Hrule
    all_goals repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
    all_goals first
      | exact ⟨_, _, spec_in_clk s _ (by rw [← Hψ.e_clk]; assumption), existSR_reflexive, in_clk Hψ _ ‹_›⟩
      | exact ⟨_, _, spec_in_d s _ (by rw [← Hψ.e_d]; assumption), existSR_reflexive, in_d Hψ _ ‹_›⟩
      | exact ⟨_, _, spec_in_clrn s _ (by rw [← Hψ.e_crn]; assumption), existSR_reflexive, in_clrn Hψ _ ‹_›⟩
  · intro ident mid_i v Hrule
    obtain ⟨crF_in, ⟨s2_clk, s2_d, s2_clrn, s2_qh⟩, clkF_in, ⟨s1_clk, s1_d, s1_clrn, s1_qh⟩⟩ := i
    dsimp only [ψ] at Hψ
    obtain ⟨m_crF_in, ⟨m_s2_clk, m_s2_d, m_s2_clrn, m_s2_qh⟩, m_clkF_in, ⟨m_s1_clk, m_s1_d, m_s1_clrn, m_s1_qh⟩⟩ := mid_i
    case_transition Hcontains : Module.outputs syncNetlist, ident, (PortMap.getIO_not_contained_false' Hrule)
    dsimp only [syncNetlist] at Hcontains
    simp at Hcontains
    subst Hcontains
    rw [PortMap.rw_rule_execution (by dsimp [reducePortMapgetIO])] at Hrule
    dsimp only at Hrule
    simp only [Prod.mk.injEq, and_assoc] at Hrule
    repeat' (obtain ⟨h, Hrule⟩ := Hrule; try subst h)
    exact ⟨s, _, existSR_reflexive, spec_out_q s _ (Hψ.e_qh ▸ ‹_›) (out_q Hψ ‹_›), out_wf Hψ⟩
  · intro rule mid_i Hin Hrule
    rw [syncNetlist_internals_eq] at Hin
    simp only [List.mem_cons, List.not_mem_nil, or_false] at Hin
    rcases Hin with h | h | h | h | h
    · subst h; exact int_case_0 s i mid_i Hψ Hrule
    · subst h; exact int_case_1 s i mid_i Hψ Hrule
    · subst h; exact int_case_2 s i mid_i Hψ Hrule
    · subst h; exact int_case_3 s i mid_i Hψ Hrule
    · subst h; exact int_case_4 s i mid_i Hψ Hrule

theorem refines_initial : Module.refines_initial syncNetlist syncSpec ψ := by
  intro i hi
  obtain ⟨crF_in, ⟨s2_clk, s2_d, s2_clrn, s2_qh⟩, clkF_in, ⟨s1_clk, s1_d, s1_clrn, s1_qh⟩⟩ := i
  dsimp only [syncNetlist] at hi
  simp only [Prod.mk.injEq, and_assoc] at hi
  obtain ⟨rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩ := hi
  exact ⟨([], [], [], []), rfl, Wf.init⟩

/-- **The two registers refine the synchroniser's netlist block.** -/
theorem sync_refines : syncNetlist ⊑ syncSpec :=
  ⟨inferInstance, ψ, refines_ψ, refines_initial⟩

end Graphiti.AsyncFifo.Sync
