name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Cache `.lake` folder
        id: cache-lake
        uses: actions/cache@v4
        with:
          path: .lake
          key: ${{ runner.os }}-lake-${{ hashFiles('lake-manifest.json') }}-4

      - name: Get mathlib cache
        continue-on-error: true
        run: |
          (make setup; true)

      - name: verify `lake build GraphitiCore` works
        run: |
          lake build GraphitiCore

      - name: verify `lake build GraphitiProjects` works
        run: |
          lake build GraphitiProjects

      - name: run tests using `lake test`
        run: |
          lake test

      - name: install `rust` for the oracle
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: installing oracle and building graphiti
        run: |
          make build-exe

      - name: verify `lake exe graphiti -h` works
        run: |
          lake exe graphiti -h

      - name: test GCD example
        run: |
          lake exe graphiti benchmarks/post-processed/gcd.dot -o out.dot --oracle $(pwd)/bin/graphiti_oracle --reverse

      - name: test matvec example
        run: |
          lake exe graphiti benchmarks/post-processed/matvec.dot -o out.dot --oracle $(pwd)/bin/graphiti_oracle --reverse

      - name: test gemm example
        run: |
          lake exe graphiti benchmarks/post-processed/gemm.dot -o out.dot --oracle $(pwd)/bin/graphiti_oracle --reverse

      - name: test gsum_many example
        run: |
          lake exe graphiti benchmarks/post-processed/gsum_many.dot -o out.dot --oracle $(pwd)/bin/graphiti_oracle --reverse
